# Where `just install` puts the `siana` command.
bindir := env('XDG_BIN_HOME', env('HOME') / '.local/bin')
# Where a SIANA instance keeps its queue and its configuration.
home := env('SIANA_HOME', env('HOME') / '.siana')

[private]
default:
    @just --list

# Create SIANA's home: the fleet queue, its instructions, and its pi session
init: _contract-drift
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # Stop safely and report when the world surprises us, rather than guessing.
    for cmd in pi tasks; do
        command -v "$cmd" >/dev/null || {
            echo "missing: $cmd" >&2
            [ "$cmd" = tasks ] && echo "  run \`just install\` in the tasks checkout" >&2
            exit 1
        }
    done

    mkdir -p "$home"

    # Config is a flat env file: readable, hand-editable, and the whole of what
    # SIANA needs to find itself. Regenerated on every init because it is derived.
    datafile="$(command -v datafile || true)"
    {
        echo "# Generated by \`just init\` in $distro. Safe to edit."
        echo "SIANA_HOME=$home"
        echo "SIANA_DISTRO=$distro"
        [ -n "$datafile" ] && echo "TASKS_DATAFILE=$(readlink "$datafile" || echo "$datafile")"
    } > "$home/siana.env"

    # SIANA can evolve its own instructions, the orders its minions are started with,
    # and the brief templates it scaffolds a task contract from, so a home copy that
    # has diverged is the captain's work, not drift to be cleaned up. Never clobber it.
    for f in AGENTS.md orders.md brief-ship.md brief-scout.md brief-qa.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "wrote    $home/$f"
        elif ! cmp -s "$distro/template/$f" "$home/$f"; then
            echo "kept     $home/$f (differs from the distro template)"
        else
            echo "current  $home/$f"
        fi
    done

    # The captain's project registry and SIANA's obligations: datafile stores like
    # the queue. The contract is what says each store exists, because the `.jsonl`
    # itself is written by the first `datafile put`, so an empty store is a schema
    # and no log. Never overwritten, for the reason the queue's contract is not: a
    # field dropped from a live contract makes every record carrying it unreadable.
    for c in schema-projects schema-obligations; do
        if [ -f "$home/$c.yaml" ]; then
            echo "current  $home/$c.yaml"
        else
            cp "$distro/template/$c.yaml" "$home/$c.yaml"
            echo "wrote    $home/$c.yaml"
        fi
    done

    # The registry used to be a hand-edited projects.yaml. Say so rather than leave
    # a file that still looks authoritative but is read by nothing.
    if [ -f "$home/projects.yaml" ]; then
        echo "  stale   $home/projects.yaml is no longer read" >&2
        echo "          the registry is now $home/projects.jsonl; move any projects" >&2
        echo "          across with \`datafile -f projects.jsonl put --set ...\`, then" >&2
        echo "          delete the old file" >&2
    fi

    # The queue. `tasks init` writes the schema contract; tasks.jsonl itself is
    # created by the first append, so the schema is what says the store exists.
    if [ -f "$home/schema-tasks.yaml" ]; then
        echo "current  $home/schema-tasks.yaml"
    else
        (cd "$home" && tasks init >/dev/null)
        echo "wrote    $home/schema-tasks.yaml"
    fi

    # Project-local, never global: SIANA's session opens with the queue in front
    # of it, and no other agent session on this machine sees fleet-wide state.
    pkg="$distro/../tasks/pi-agent-tasks"
    if [ -d "$pkg" ]; then
        # -a because pi refuses to rewrite an existing project-local config in an
        # untrusted directory, and re-running init must not be a first-run-only path.
        (cd "$home" && pi install -l -a "$(cd "$pkg" && pwd)" >/dev/null)
        echo "wrote    $home/.pi/settings.json"
    else
        echo "skipped  ambient queue: no pi package at $pkg" >&2
        echo "         run \`tasks pi-package\` in the tasks checkout, then re-run init" >&2
    fi

    mkdir -p '{{bindir}}'
    for c in siana siana-dispatch siana-brief siana-watch siana-owe siana-publish siana-reap; do
        ln -sfn "$distro/bin/$c" "{{bindir}}/$c"
        echo "linked   {{bindir}}/$c -> $distro/bin/$c"
    done

    # Linking is not the whole install; say nothing worked until it has.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }
    case ":$PATH:" in
        *":{{bindir}}:"*) echo; echo "SIANA is ready. Run \`siana\` to take the helm." ;;
        *) echo; echo "{{bindir}} is not on your PATH. Add to your shell profile:"
           echo '  export PATH="'{{bindir}}':$PATH"' ;;
    esac

# Refuse to upgrade a home that was never created. An upgrade is not an install,
# and `init` would happily build one here, turning a typo in SIANA_HOME into a
# fresh empty fleet that looks like a successful upgrade.
[private]
_initialized:
    #!/usr/bin/env bash
    set -euo pipefail
    [ -f '{{home}}/siana.env' ] || {
        echo "no SIANA home at {{home}}" >&2
        echo "  run \`just init\` to create one" >&2
        exit 1
    }

# Bring an already-created SIANA home up to date with this distro
upgrade: _initialized init
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # `init` has already run, and is idempotent: it regenerates siana.env, refreshes
    # the pi package, and re-links the commands. Depending on it rather than
    # repeating it is what keeps an upgrade from drifting away from an install.

    # Distro-owned instructions. SIANA can evolve its home copy, so a diverged
    # file is real work, never drift to be cleaned up: it is preserved before the
    # template lands, with the diff beside it. Nothing is merged here. Reconciling
    # instructions is reading what they mean, which is an agent's job and not a
    # script's, and conflict markers in AGENTS.md would poison SIANA's own prompt.
    stamp="$(date +%Y%m%d-%H%M%S)"
    backup="$home/upgrade/$stamp"
    kept=""
    echo
    for f in AGENTS.md orders.md brief-ship.md brief-scout.md brief-qa.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "restored $home/$f (it was missing)"
        elif cmp -s "$distro/template/$f" "$home/$f"; then
            echo "current  $home/$f"
        else
            mkdir -p "$backup"
            cp "$home/$f" "$backup/$f"
            # diff exits 1 because they differ, which is the whole reason we are here.
            diff -u "$home/$f" "$distro/template/$f" > "$backup/$f.diff" || true
            cp "$distro/template/$f" "$home/$f"
            echo "upgraded $home/$f"
            kept="$kept$f"$'\n'
        fi
    done

    # The registry's records are the captain's data and never the distro's, so an
    # upgrade has nothing to say about them. Neither contract is rewritten either: a
    # field dropped from a live contract makes every record still carrying it
    # unreadable, so a contract only ever grows, by hand, once the captain has seen
    # what it would cost. Task-contract drift is reported by `_contract-drift`;
    # project-contract drift announces itself, because `datafile` names the field it
    # rejected and `siana` refuses to start on a registry it cannot read.
    echo "kept     $home/projects.jsonl (the captain's registry)"
    for c in schema-projects schema-obligations schema-tasks; do
        echo "kept     $home/$c.yaml (rewriting a live contract loses records)"
    done

    # Say nothing worked until the queue has been read through the upgraded home.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }

    if [ -n "$kept" ]; then
        echo
        echo "Your copy of each upgraded file is preserved in"
        echo "  $backup"
        echo "with a .diff beside it showing what this upgrade changed:"
        printf '%s' "$kept" | while read -r f; do echo "  $f"; echo "  $f.diff"; done
        echo
        echo "Re-apply anything you still want, then delete that directory."
    fi

# Warn when the home's task contract predates the installed `tasks`. A field the
# CLI writes but the contract lacks is rejected by `extra: forbid` as a raw
# traceback, so this has to be caught here rather than discovered at `add`.
[private]
_contract-drift:
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'

    # A field the distro's project contract has and the home copy does not is a
    # setting the captain cannot make: `extra: forbid` refuses the write and names
    # the key, without saying that the contract is simply older than the field. An
    # upgrade never rewrites a live contract, because a dropped field makes every
    # record still carrying it unreadable, so growing one stays the captain's call
    # and this only makes sure they know there is one to make.
    if [ -f "$home/schema-projects.yaml" ]; then
        absent="$(comm -13 \
            <(grep -oE '^  [a-z_]+:' "$home/schema-projects.yaml" | tr -d ' :' | sort) \
            <(grep -oE '^  [a-z_]+:' "$PWD/template/schema-projects.yaml" | tr -d ' :' | sort))"
        if [ -n "$absent" ]; then
            echo "  stale   schema-projects.yaml is missing: $(echo $absent | tr '\n' ' ')" >&2
            echo "          copy those fields into $home/schema-projects.yaml from" >&2
            echo "          $PWD/template/schema-projects.yaml; until then the registry" >&2
            echo "          refuses to record them" >&2
        fi
    fi

    [ -f "$home/schema-tasks.yaml" ] || exit 0
    fresh="$(mktemp -d)"
    (cd "$fresh" && tasks init >/dev/null 2>&1) || exit 0
    missing="$(comm -13 \
        <(grep -oE '^  [a-z_]+:' "$home/schema-tasks.yaml" | tr -d ' :' | sort) \
        <(grep -oE '^  [a-z_]+:' "$fresh/schema-tasks.yaml" | tr -d ' :' | sort))"
    rm -rf "$fresh"
    [ -z "$missing" ] && exit 0
    echo "  stale   schema-tasks.yaml is missing: $(echo $missing | tr '\n' ' ')" >&2
    echo "          add those fields to $home/schema-tasks.yaml" >&2
    echo "          until then every task the CLI writes is rejected by the" >&2
    echo "          contract, which is a traceback rather than a refusal" >&2

# Run the distro's tests. Pass unittest arguments through: `just test -v`, or
# `just test -k slug` for one rule.
test *args:
    #!/usr/bin/env bash
    set -euo pipefail
    # `-s tests` and no `-t` so the suite's own helpers import by name. Nothing is
    # installed to run these: they drive the commands where the mechanics are pure,
    # and drive them as processes against a real `tasks` and `datafile` where they
    # are not, because a stubbed store would only ever agree with this suite.
    python3 -m unittest discover -s tests {{args}}

# Report SIANA's state without changing anything
doctor: _contract-drift
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'
    echo "home     $home"
    for f in siana.env AGENTS.md orders.md brief-ship.md brief-scout.md brief-qa.md schema-projects.yaml schema-obligations.yaml schema-tasks.yaml .pi/settings.json; do
        if [ -e "$home/$f" ]; then echo "  ok      $f"; else echo "  missing $f"; fi
    done
    # An empty queue has no tasks.jsonl at all: datafile creates it on the first
    # append. Absent is the zero, not a fault, and doctor must not cry wolf.
    if [ -e "$home/tasks.jsonl" ]; then echo "  ok      tasks.jsonl"
    elif [ -e "$home/schema-tasks.yaml" ]; then echo "  ok      tasks.jsonl (empty; written on the first task)"
    else echo "  missing tasks.jsonl"; fi
    if [ -e "$home/projects.jsonl" ]; then echo "  ok      projects.jsonl"
    elif [ -e "$home/schema-projects.yaml" ]; then echo "  ok      projects.jsonl (empty; written on the first project)"
    else echo "  missing projects.jsonl"; fi
    if [ -e "$home/obligations.jsonl" ]; then echo "  ok      obligations.jsonl"
    elif [ -e "$home/schema-obligations.yaml" ]; then echo "  ok      obligations.jsonl (empty; written on the first promise)"
    else echo "  missing obligations.jsonl"; fi
    for cmd in pi tasks datafile; do
        p="$(command -v "$cmd" || true)"
        if [ -n "$p" ]; then echo "  ok      $cmd -> $p"; else echo "  missing $cmd"; fi
    done
    # One SIANA leads the fleet, so which one is a thing the captain can ask about.
    # No session is the ordinary state between sessions and never a fault; a session
    # whose pid is gone is one killed before its trap ran, and blocks the next start.
    pid="$(sed -n 's/^SIANA_PID=//p' "$home/session" 2>/dev/null)"
    pane="$(sed -n 's/^SIANA_PANE=//p' "$home/session" 2>/dev/null)"
    if [ -z "$pid" ]; then
        echo "  ok      no SIANA running"
    elif ! kill -0 "$pid" 2>/dev/null; then
        echo "  stale   session claims pid $pid, which is gone" >&2
        echo "          remove $home/session to start a new SIANA" >&2
    else
        echo "  ok      SIANA running (pid $pid${pane:+, pane $pane})"
    fi
    # Whether the fleet advances while the captain is away. The watcher owns its own
    # record, so it is asked rather than parsed here: a file can say a watcher was
    # started and never that one is running, and only the command that wrote it knows
    # how to tell those apart. It reports and never repairs, because removing a
    # stopped watcher's record is deciding the captain has read it.
    SIANA_HOME="$home" "$PWD/bin/siana-watch" --status || true
    # Dispatch does the resolving and holds the pane bindings, so asking it means
    # this cannot drift from what a real dispatch would accept or from where a real
    # minion was put. It reports a dead owner and never reclaims one: `tasks reset`
    # stays manual because a dead minion's worktree may hold unlanded work.
    echo
    SIANA_HOME="$home" "$PWD/bin/siana-dispatch" --check || true
    echo
    SIANA_HOME="$home" "$PWD/bin/siana-owe" || true
    echo
    [ -d "$home" ] && (cd "$home" && tasks)

# Remove the installed commands. SIANA's home and its queue are left alone.
uninstall:
    #!/usr/bin/env bash
    set -euo pipefail
    for c in siana siana-dispatch siana-brief siana-watch siana-owe siana-publish siana-reap; do
        link="{{bindir}}/$c"
        if [ ! -L "$link" ] && [ ! -e "$link" ]; then
            echo "not installed: $link"
        elif [ "$(readlink "$link" || true)" = "$PWD/bin/$c" ]; then
            rm "$link"
            echo "removed $link"
        else
            echo "refusing to remove $link: not a link to $PWD/bin/$c" >&2
            exit 1
        fi
    done
    echo "kept    {{home}} (delete it by hand; it holds the queue)"
