# Where `just install` puts the `siana` command.
bindir := env('XDG_BIN_HOME', env('HOME') / '.local/bin')
# Where a SIANA instance keeps its queue and its configuration.
home := env('SIANA_HOME', env('HOME') / '.siana')

[private]
default:
    @just --list

# Create SIANA's home: the fleet queue, its instructions, and its pi session
init: _contract-drift
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # Stop safely and report when the world surprises us, rather than guessing.
    for cmd in pi tasks; do
        command -v "$cmd" >/dev/null || {
            echo "missing: $cmd" >&2
            [ "$cmd" = tasks ] && echo "  run \`just install\` in the tasks checkout" >&2
            exit 1
        }
    done

    mkdir -p "$home"

    # Config is a flat env file: readable, hand-editable, and the whole of what
    # SIANA needs to find itself. Regenerated on every init because it is derived.
    datafile="$(command -v datafile || true)"
    {
        echo "# Generated by \`just init\` in $distro. Safe to edit."
        echo "SIANA_HOME=$home"
        echo "SIANA_DISTRO=$distro"
        [ -n "$datafile" ] && echo "TASKS_DATAFILE=$(readlink "$datafile" || echo "$datafile")"
    } > "$home/siana.env"

    # SIANA can evolve its own instructions and the orders its minions are started
    # with, so a home copy that has diverged is the captain's work, not drift to be
    # cleaned up. Never clobber it.
    for f in AGENTS.md orders.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "wrote    $home/$f"
        elif ! cmp -s "$distro/template/$f" "$home/$f"; then
            echo "kept     $home/$f (differs from the distro template)"
        else
            echo "current  $home/$f"
        fi
    done

    # The captain's project registry, a datafile store like the queue. The contract
    # is what says the registry exists: projects.jsonl itself is written by the first
    # `datafile put`, so an empty registry is a schema and no log.
    if [ -f "$home/schema-projects.yaml" ]; then
        echo "current  $home/schema-projects.yaml"
    else
        cp "$distro/template/schema-projects.yaml" "$home/schema-projects.yaml"
        echo "wrote    $home/schema-projects.yaml"
    fi

    # The registry used to be a hand-edited projects.yaml. Say so rather than leave
    # a file that still looks authoritative but is read by nothing.
    if [ -f "$home/projects.yaml" ]; then
        echo "  stale   $home/projects.yaml is no longer read" >&2
        echo "          the registry is now $home/projects.jsonl; move any projects" >&2
        echo "          across with \`datafile -f projects.jsonl put --set ...\`, then" >&2
        echo "          delete the old file" >&2
    fi

    # The queue. `tasks init` writes the schema contract; tasks.jsonl itself is
    # created by the first append, so the schema is what says the store exists.
    if [ -f "$home/schema-tasks.yaml" ]; then
        echo "current  $home/schema-tasks.yaml"
    else
        (cd "$home" && tasks init >/dev/null)
        echo "wrote    $home/schema-tasks.yaml"
    fi

    # Project-local, never global: SIANA's session opens with the queue in front
    # of it, and no other agent session on this machine sees fleet-wide state.
    pkg="$distro/../tasks/pi-agent-tasks"
    if [ -d "$pkg" ]; then
        # -a because pi refuses to rewrite an existing project-local config in an
        # untrusted directory, and re-running init must not be a first-run-only path.
        (cd "$home" && pi install -l -a "$(cd "$pkg" && pwd)" >/dev/null)
        echo "wrote    $home/.pi/settings.json"
    else
        echo "skipped  ambient queue: no pi package at $pkg" >&2
        echo "         run \`tasks pi-package\` in the tasks checkout, then re-run init" >&2
    fi

    mkdir -p '{{bindir}}'
    for c in siana siana-dispatch; do
        ln -sfn "$distro/bin/$c" "{{bindir}}/$c"
        echo "linked   {{bindir}}/$c -> $distro/bin/$c"
    done

    # Linking is not the whole install; say nothing worked until it has.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }
    case ":$PATH:" in
        *":{{bindir}}:"*) echo; echo "SIANA is ready. Run \`siana\` to take the helm." ;;
        *) echo; echo "{{bindir}} is not on your PATH. Add to your shell profile:"
           echo '  export PATH="'{{bindir}}':$PATH"' ;;
    esac

# Refuse to upgrade a home that was never created. An upgrade is not an install,
# and `init` would happily build one here, turning a typo in SIANA_HOME into a
# fresh empty fleet that looks like a successful upgrade.
[private]
_initialized:
    #!/usr/bin/env bash
    set -euo pipefail
    [ -f '{{home}}/siana.env' ] || {
        echo "no SIANA home at {{home}}" >&2
        echo "  run \`just init\` to create one" >&2
        exit 1
    }

# Bring an already-created SIANA home up to date with this distro
upgrade: _initialized init
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # `init` has already run, and is idempotent: it regenerates siana.env, refreshes
    # the pi package, and re-links the commands. Depending on it rather than
    # repeating it is what keeps an upgrade from drifting away from an install.

    # Distro-owned instructions. SIANA can evolve its home copy, so a diverged
    # file is real work, never drift to be cleaned up: it is preserved before the
    # template lands, with the diff beside it. Nothing is merged here. Reconciling
    # instructions is reading what they mean, which is an agent's job and not a
    # script's, and conflict markers in AGENTS.md would poison SIANA's own prompt.
    stamp="$(date +%Y%m%d-%H%M%S)"
    backup="$home/upgrade/$stamp"
    kept=""
    echo
    for f in AGENTS.md orders.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "restored $home/$f (it was missing)"
        elif cmp -s "$distro/template/$f" "$home/$f"; then
            echo "current  $home/$f"
        else
            mkdir -p "$backup"
            cp "$home/$f" "$backup/$f"
            # diff exits 1 because they differ, which is the whole reason we are here.
            diff -u "$home/$f" "$distro/template/$f" > "$backup/$f.diff" || true
            cp "$distro/template/$f" "$home/$f"
            echo "upgraded $home/$f"
            kept="$kept$f"$'\n'
        fi
    done

    # The registry's records are the captain's data and never the distro's, so an
    # upgrade has nothing to say about them. Neither contract is rewritten either: a
    # field dropped from a live contract makes every record still carrying it
    # unreadable, so a contract only ever grows, by hand, once the captain has seen
    # what it would cost. Task-contract drift is reported by `_contract-drift`;
    # project-contract drift announces itself, because `datafile` names the field it
    # rejected and `siana` refuses to start on a registry it cannot read.
    echo "kept     $home/projects.jsonl (the captain's registry)"
    for c in schema-projects schema-tasks; do
        echo "kept     $home/$c.yaml (rewriting a live contract loses records)"
    done

    # Say nothing worked until the queue has been read through the upgraded home.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }

    if [ -n "$kept" ]; then
        echo
        echo "Your copy of each upgraded file is preserved in"
        echo "  $backup"
        echo "with a .diff beside it showing what this upgrade changed:"
        printf '%s' "$kept" | while read -r f; do echo "  $f"; echo "  $f.diff"; done
        echo
        echo "Re-apply anything you still want, then delete that directory."
    fi

# Warn when the home's task contract predates the installed `tasks`. A field the
# CLI writes but the contract lacks is rejected by `extra: forbid` as a raw
# traceback, so this has to be caught here rather than discovered at `add`.
[private]
_contract-drift:
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'
    [ -f "$home/schema-tasks.yaml" ] || exit 0
    fresh="$(mktemp -d)"
    (cd "$fresh" && tasks init >/dev/null 2>&1) || exit 0
    missing="$(comm -13 \
        <(grep -oE '^  [a-z_]+:' "$home/schema-tasks.yaml" | tr -d ' :' | sort) \
        <(grep -oE '^  [a-z_]+:' "$fresh/schema-tasks.yaml" | tr -d ' :' | sort))"
    rm -rf "$fresh"
    [ -z "$missing" ] && exit 0
    echo "  stale   schema-tasks.yaml is missing: $(echo $missing | tr '\n' ' ')" >&2
    echo "          add those fields to $home/schema-tasks.yaml" >&2

# Report SIANA's state without changing anything
doctor: _contract-drift
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'
    echo "home     $home"
    for f in siana.env AGENTS.md orders.md schema-projects.yaml schema-tasks.yaml .pi/settings.json; do
        if [ -e "$home/$f" ]; then echo "  ok      $f"; else echo "  missing $f"; fi
    done
    # An empty queue has no tasks.jsonl at all: datafile creates it on the first
    # append. Absent is the zero, not a fault, and doctor must not cry wolf.
    if [ -e "$home/tasks.jsonl" ]; then echo "  ok      tasks.jsonl"
    elif [ -e "$home/schema-tasks.yaml" ]; then echo "  ok      tasks.jsonl (empty; written on the first task)"
    else echo "  missing tasks.jsonl"; fi
    if [ -e "$home/projects.jsonl" ]; then echo "  ok      projects.jsonl"
    elif [ -e "$home/schema-projects.yaml" ]; then echo "  ok      projects.jsonl (empty; written on the first project)"
    else echo "  missing projects.jsonl"; fi
    for cmd in pi tasks datafile; do
        p="$(command -v "$cmd" || true)"
        if [ -n "$p" ]; then echo "  ok      $cmd -> $p"; else echo "  missing $cmd"; fi
    done
    # The registry is hand-edited, so a bad path or bad YAML is discovered here
    # rather than halfway through starting a minion. Dispatch does the resolving,
    # so this cannot drift from what a real dispatch would accept.
    echo
    SIANA_HOME="$home" "$PWD/bin/siana-dispatch" --check || true
    echo
    [ -d "$home" ] && (cd "$home" && tasks)

# Remove the installed commands. SIANA's home and its queue are left alone.
uninstall:
    #!/usr/bin/env bash
    set -euo pipefail
    for c in siana siana-dispatch; do
        link="{{bindir}}/$c"
        if [ ! -L "$link" ] && [ ! -e "$link" ]; then
            echo "not installed: $link"
        elif [ "$(readlink "$link" || true)" = "$PWD/bin/$c" ]; then
            rm "$link"
            echo "removed $link"
        else
            echo "refusing to remove $link: not a link to $PWD/bin/$c" >&2
            exit 1
        fi
    done
    echo "kept    {{home}} (delete it by hand; it holds the queue)"
