# Where `just install` puts the `siana` command.
bindir := env('XDG_BIN_HOME', env('HOME') / '.local/bin')
# Where a SIANA instance keeps its queue and its configuration.
home := env('SIANA_HOME', env('HOME') / '.siana')
# The tasks pi package, which puts the queue in front of SIANA's session. Empty
# means `just init` generates one into the home from the installed `tasks`; set it
# only to point at a package directory you keep yourself.
pi_package := env('SIANA_PI_PACKAGE', '')

[private]
default:
    @just --list

# Create SIANA's home: the fleet queue, its instructions, and its pi session
init: _contract-drift
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # Stop safely and report when the world surprises us, rather than guessing.
    command -v tasks >/dev/null || {
        echo "missing: tasks" >&2
        echo "  run \`just install\` in the tasks checkout" >&2
        exit 1
    }

    # SIANA's session runs in pi or in claude, and each needs a different queue
    # integration in the home, so init writes one for every harness it finds
    # rather than choosing. Which one a session opens in is `siana --harness`, and
    # a home with both installed answers to either without another init.
    #
    # Neither present is a stop. `siana` refuses to start in a harness whose
    # integration is not there, so an install that wrote none at all is a home the
    # captain can only find out about at the helm.
    have_pi=""; have_claude=""
    if command -v pi >/dev/null; then have_pi=1; fi
    if command -v claude >/dev/null; then have_claude=1; fi
    if [ -z "$have_pi$have_claude" ]; then
        echo "missing: pi and claude" >&2
        echo "  SIANA's session runs in one of them; install at least one" >&2
        echo "  \`brew install pi-coding-agent\`, or install Claude Code" >&2
        exit 1
    fi

    # A configured package that is not there is a refusal, never a fallback. The
    # captain naming a directory means they want that package; generating a
    # different one behind their back would give SIANA a queue skill that is not
    # the one they are editing. Checked before anything is written, so a typo in
    # SIANA_PI_PACKAGE costs a retype and not a half-built home.
    #
    # Two ways to get it wrong, and the second is the likelier one. A path that is
    # not there is a typo. A directory that is there and holds no package.json is
    # the near miss: the tasks checkout root rather than the `pi-agent-tasks`
    # inside it. `pi install -l -a` takes any directory without complaint, so that
    # one used to exit 0 with a settings.json naming it, `pi package list` showing
    # nothing, and `doctor` calling the home complete - the silently queueless home
    # this whole recipe exists to prevent. package.json is what makes a directory a
    # pi package, and it is what `tasks pi-package --out` writes.
    #
    # Naming one with no pi to install it into is refused for the same reason, and
    # not skipped as harmless: the captain who set it is expecting a pi session,
    # and an init that quietly wrote a claude home instead would answer a question
    # they did not ask.
    pkg='{{pi_package}}'
    if [ -n "$pkg" ] && [ -z "$have_pi" ]; then
        echo "SIANA_PI_PACKAGE is set and pi is not installed" >&2
        echo "  install pi, or unset it to install for the harnesses you have" >&2
        exit 1
    fi
    problem=""
    if [ -n "$pkg" ] && [ ! -d "$pkg" ]; then
        problem="no pi package directory at $pkg"
    elif [ -n "$pkg" ] && [ ! -f "$pkg/package.json" ]; then
        problem="not a pi package: no package.json in $pkg"
    fi
    if [ -n "$problem" ]; then
        echo "$problem" >&2
        echo "  SIANA_PI_PACKAGE must name a directory holding the tasks pi package" >&2
        echo "  \`tasks pi-package --out <dir>\` writes one; unset it to have init" >&2
        echo "  generate one into $home" >&2
        exit 1
    fi

    mkdir -p "$home"

    # Config is a flat env file: readable, hand-editable, and the whole of what
    # SIANA needs to find itself. Regenerated on every init because it is derived.
    datafile="$(command -v datafile || true)"
    {
        echo "# Generated by \`just init\` in $distro. Safe to edit."
        echo "SIANA_HOME=$home"
        echo "SIANA_DISTRO=$distro"
        [ -n "$datafile" ] && echo "TASKS_DATAFILE=$(readlink "$datafile" || echo "$datafile")"
    } > "$home/siana.env"

    # SIANA can evolve its own instructions, the orders its minions are started with,
    # the brief templates it scaffolds a task contract from, and the handoff a minion
    # writes the merge request in, so a home copy that has diverged is the captain's
    # work, not drift to be cleaned up. Never clobber it.
    for f in AGENTS.md orders.md review.md brief-ship.md brief-scout.md brief-qa.md handoff.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "wrote    $home/$f"
        elif ! cmp -s "$distro/template/$f" "$home/$f"; then
            echo "kept     $home/$f (differs from the distro template)"
        else
            echo "current  $home/$f"
        fi
    done

    # The captain's project registry and SIANA's obligations: datafile stores like
    # the queue. The contract is what says each store exists, because the `.jsonl`
    # itself is written by the first `datafile put`, so an empty store is a schema
    # and no log. Never overwritten, for the reason the queue's contract is not: a
    # field dropped from a live contract makes every record carrying it unreadable.
    for c in schema-projects schema-obligations schema-decisions; do
        if [ -f "$home/$c.yaml" ]; then
            echo "current  $home/$c.yaml"
        else
            cp "$distro/template/$c.yaml" "$home/$c.yaml"
            echo "wrote    $home/$c.yaml"
        fi
    done

    # The captain's principles. Never overwritten and never upgraded, for a reason
    # neither the instructions nor the contracts have: it is the only file an
    # advisory session lets SIANA read a principle from, and a distro that could
    # rewrite it could rewrite what SIANA is held to. It ships with its placeholder
    # unfilled, and `siana-afk` refuses to start while that placeholder is there, so
    # a home that has never had principles written cannot run a night of proposals
    # justified by a template.
    if [ -f "$home/principles.md" ]; then
        echo "kept     $home/principles.md (your principles)"
    else
        cp "$distro/template/principles.md" "$home/principles.md"
        echo "wrote    $home/principles.md"
    fi

    # The registry used to be a hand-edited projects.yaml. Say so rather than leave
    # a file that still looks authoritative but is read by nothing.
    if [ -f "$home/projects.yaml" ]; then
        echo "  stale   $home/projects.yaml is no longer read" >&2
        echo "          the registry is now $home/projects.jsonl; move any projects" >&2
        echo "          across with \`datafile -f projects.jsonl put --set ...\`, then" >&2
        echo "          delete the old file" >&2
    fi

    # The queue. `tasks init` writes the schema contract; tasks.jsonl itself is
    # created by the first append, so the schema is what says the store exists.
    if [ -f "$home/schema-tasks.yaml" ]; then
        echo "current  $home/schema-tasks.yaml"
    else
        (cd "$home" && tasks init >/dev/null)
        echo "wrote    $home/schema-tasks.yaml"
    fi

    # Project-local, never global: SIANA's session opens with the queue in front
    # of it, and no other agent session on this machine sees fleet-wide state.
    #
    # The package is generated from the installed `tasks`, not found beside the
    # checkout. A sibling `../tasks/pi-agent-tasks` is a layout one machine happened
    # to have, so the ambient queue was an install step nobody else could complete,
    # and it failed by skipping - leaving a home that looked installed and had no
    # queue in front of it. Generated is also the only way it stays correct: the
    # package bakes in the absolute path of the `tasks` it came from, so one found
    # on disk can point at a different one. Regenerated on every init, like
    # siana.env, because it is derived and never the captain's work.
    if [ -n "$have_pi" ]; then
        if [ -z "$pkg" ]; then
            pkg="$home/pi-agent-tasks"
            tasks pi-package --out "$pkg" >/dev/null || {
                echo "cannot generate the pi package with $(command -v tasks)" >&2
                echo "  \`tasks pi-package --out <dir>\` is how the ambient queue is built" >&2
                echo "  upgrade tasks until it works, or set SIANA_PI_PACKAGE to a" >&2
                echo "  package directory you already have" >&2
                exit 1
            }
            echo "wrote    $pkg"
        fi
        # Every queue package already configured here is removed before the one
        # this init installs is added, because `pi install` only appends a source
        # and never drops another package that carries the same skill from a
        # different path. So a home inited once with SIANA_PI_PACKAGE pointing at a
        # tasks checkout and again without it kept both entries, pi resolved the
        # resulting skill collision first-wins, and the stale one won - leaving
        # SIANA reading its queue skill from the package the captain had stopped
        # configuring, whose every documented command named a `tasks` that was not
        # on PATH. It surfaced as a startup warning and nowhere else: `doctor` does
        # not read the packages list, so that home reported complete. Init owns
        # this list rather than adding to it.
        #
        # Only packages carrying the queue skill, and that skill is what is looked
        # for rather than a name or a path: it is the thing that actually collides,
        # and a package directory can be called anything. Anything else the captain
        # installed locally in this home is theirs and is never touched.
        #
        # Handed to `pi remove` resolved, because it matches a source by the path
        # it resolves to and not by package name: the string as stored is relative
        # to `.pi/`, and a bare name resolves against $PWD, so both quietly match
        # nothing. Its exit code is not trusted either - nothing to remove is exit
        # 1, which is the ordinary state of a first install.
        #
        # A settings.json pi cannot be read from is a stop and never an empty list:
        # taken as empty, init would append beside whatever is in there and rebuild
        # the collision it is here to remove.
        settings="$home/.pi/settings.json"
        if ! configured="$(just _pi-packages "$settings" 2>&1)"; then
            echo "$settings is not readable as pi's settings" >&2
            echo "$configured" >&2
            echo "  pi wrote it and pi reads it; repair or delete it, then run" >&2
            echo "  init again" >&2
            exit 1
        fi
        printf '%s\n' "$configured" | while IFS= read -r source; do
            [ -n "$source" ] \
                && [ -f "$source/skills/agent-tasks/SKILL.md" ] || continue
            (cd "$home" && pi remove -l -a "$source" >/dev/null 2>&1 || true)
        done
        # -a because pi refuses to rewrite an existing project-local config in an
        # untrusted directory, and re-running init must not be a first-run-only path.
        (cd "$home" && pi install -l -a "$(cd "$pkg" && pwd)" >/dev/null)
        echo "wrote    $home/.pi/settings.json"

        # The wake consumer. `siana-watch` no longer types into SIANA's pane - that
        # concatenated the captain's unsubmitted draft with the wake and submitted
        # both - so it raises a counter under $home/wake and this extension is what
        # reads it and delivers the wake inside the session. Without it the watcher
        # refuses to start, so this is not an optional extra.
        #
        # `.pi/extensions/*.ts` is a documented pi auto-discovery location, `siana`
        # runs in $home so that is the project directory, and it starts pi with
        # --approve, which is the project-local trust that gates loading it.
        #
        # Never into $home/pi-agent-tasks: `tasks pi-package` regenerates that
        # directory on every init and anything added there is lost. Overwritten
        # every time, like siana.env and the package, because it is the distro's
        # file and never the captain's work.
        mkdir -p "$home/.pi/extensions"
        cp "$distro/template/wake.ts" "$home/.pi/extensions/wake.ts"
        echo "wrote    $home/.pi/extensions/wake.ts"
    fi

    # The same two halves the pi package carries in one, which is why both are
    # installed and not just the skill: `setup` writes the SessionStart hook that
    # puts the queue in front of the session unasked, and `skill` writes the one
    # SIANA reads when it goes looking. A home with only the skill opens a session
    # that has to remember to ask, which is the thing an ambient queue replaces.
    #
    # --scope project for the reason the pi package is installed locally: the
    # files land in the home, so no other claude session on this machine sees
    # fleet-wide state.
    if [ -n "$have_claude" ]; then
        (cd "$home" \
            && tasks setup --scope project --app claude >/dev/null \
            && tasks skill --install --scope project --app claude >/dev/null) || {
            echo "cannot install the claude queue integration with $(command -v tasks)" >&2
            echo "  \`tasks setup --app claude\` writes the ambient queue and" >&2
            echo "  \`tasks skill --install --app claude\` the skill beside it" >&2
            echo "  upgrade tasks until both work" >&2
            exit 1
        }
        echo "wrote    $home/.claude/settings.json"
        echo "wrote    $home/.claude/skills/agent-tasks/SKILL.md"
    fi

    mkdir -p '{{bindir}}'
    for c in siana siana-dispatch siana-brief siana-watch siana-owe siana-retire siana-handoff siana-publish siana-reap siana-pipeline siana-afk siana-gate siana-read siana-console; do
        ln -sfn "$distro/bin/$c" "{{bindir}}/$c"
        echo "linked   {{bindir}}/$c -> $distro/bin/$c"
    done

    # Linking is not the whole install; say nothing worked until it has.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }
    case ":$PATH:" in
        *":{{bindir}}:"*) echo; echo "SIANA is ready. Run \`siana\` to take the helm." ;;
        *) echo; echo "{{bindir}} is not on your PATH. Add to your shell profile:"
           echo '  export PATH="'{{bindir}}':$PATH"' ;;
    esac

# Refuse to upgrade a home that was never created. An upgrade is not an install,
# and `init` would happily build one here, turning a typo in SIANA_HOME into a
# fresh empty fleet that looks like a successful upgrade.
[private]
_initialized:
    #!/usr/bin/env bash
    set -euo pipefail
    [ -f '{{home}}/siana.env' ] || {
        echo "no SIANA home at {{home}}" >&2
        echo "  run \`just init\` to create one" >&2
        exit 1
    }

# Bring an already-created SIANA home up to date with this distro
upgrade: _initialized init
    #!/usr/bin/env bash
    set -euo pipefail
    distro="$PWD"
    home='{{home}}'

    # `init` has already run, and is idempotent: it regenerates siana.env, refreshes
    # the pi package, and re-links the commands. Depending on it rather than
    # repeating it is what keeps an upgrade from drifting away from an install.

    # Distro-owned instructions. SIANA can evolve its home copy, so a diverged
    # file is real work, never drift to be cleaned up: it is preserved before the
    # template lands, with the diff beside it. Nothing is merged here. Reconciling
    # instructions is reading what they mean, which is an agent's job and not a
    # script's, and conflict markers in AGENTS.md would poison SIANA's own prompt.
    stamp="$(date +%Y%m%d-%H%M%S)"
    backup="$home/upgrade/$stamp"
    kept=""
    echo
    for f in AGENTS.md orders.md review.md brief-ship.md brief-scout.md brief-qa.md handoff.md; do
        if [ ! -f "$home/$f" ]; then
            cp "$distro/template/$f" "$home/$f"
            echo "restored $home/$f (it was missing)"
        elif cmp -s "$distro/template/$f" "$home/$f"; then
            echo "current  $home/$f"
        else
            mkdir -p "$backup"
            cp "$home/$f" "$backup/$f"
            # diff exits 1 because they differ, which is the whole reason we are here.
            diff -u "$home/$f" "$distro/template/$f" > "$backup/$f.diff" || true
            cp "$distro/template/$f" "$home/$f"
            echo "upgraded $home/$f"
            kept="$kept$f"$'\n'
        fi
    done

    # The registry's records are the captain's data and never the distro's, so an
    # upgrade has nothing to say about them. Neither contract is rewritten either: a
    # field dropped from a live contract makes every record still carrying it
    # unreadable, so a contract only ever grows, by hand, once the captain has seen
    # what it would cost. `_contract-drift` reports both, above, because this recipe
    # reaches it through `init` - and it is what announces project-contract drift
    # now that `siana` starts on a home whose contract predates `automerge` instead
    # of refusing. `siana` says it again in a `stale` line at every start, so the
    # captain meets it where the setting they cannot make would be made, and
    # `datafile` still names the field it rejected at the write.
    echo "kept     $home/projects.jsonl (the captain's registry)"
    for c in schema-projects schema-obligations schema-decisions schema-tasks; do
        echo "kept     $home/$c.yaml (rewriting a live contract loses records)"
    done
    # Never upgraded either, and for a different reason: a distro that could rewrite
    # the principles could rewrite what SIANA is held to while the captain is away.
    echo "kept     $home/principles.md (your principles)"

    # Say nothing worked until the queue has been read through the upgraded home.
    (cd "$home" && tasks >/dev/null) || { echo "the queue is not readable from $home" >&2; exit 1; }

    if [ -n "$kept" ]; then
        echo
        echo "Your copy of each upgraded file is preserved in"
        echo "  $backup"
        echo "with a .diff beside it showing what this upgrade changed:"
        printf '%s' "$kept" | while read -r f; do echo "  $f"; echo "  $f.diff"; done
        echo
        echo "Re-apply anything you still want, then delete that directory."
    fi

# The pi packages a home has configured, one resolved absolute path per line.
#
# Shared by `init`, which removes the queue ones before installing the package it
# was asked for, and by `doctor`, which counts them. One reader rather than two
# that have to agree: a doctor reporting on a different list than init writes is
# worse than no report at all.
#
# Resolved, because a source as stored is relative to `.pi/` and both callers need
# a path they can test from somewhere else. No settings file is no packages and
# exits 0, which is the ordinary state of a home before its first install. One
# that cannot be read exits nonzero with the one line json gives for why, for the
# caller to refuse on rather than read as empty. A traceback is what every other
# read in this file is written to keep off the captain's screen.
#
# `if 1:` so the reader can be indented as a recipe line without python calling
# that an indentation error: just ends a recipe at the first unindented line, and
# a heredoc terminator cannot be indented with spaces.
#
# `[no-exit-message]` because both callers report the failure themselves, and
# just's own "recipe failed" line arrives inside the text they are quoting.
[private]
[no-exit-message]
_pi-packages settings:
    #!/usr/bin/env bash
    set -euo pipefail
    [ -f '{{settings}}' ] || exit 0
    python3 -c 'if 1:
        import json, os, sys
        try:
            with open(sys.argv[1]) as fh:
                sources = json.load(fh).get("packages", [])
        except (OSError, ValueError) as why:
            sys.exit(str(why))
        base = os.path.dirname(os.path.abspath(sys.argv[1]))
        for source in sources:
            print(os.path.abspath(os.path.join(base, source)))
        ' '{{settings}}'

# Warn when the home's task contract predates the installed `tasks`. A field the
# CLI writes but the contract lacks is rejected by `extra: forbid` as a raw
# traceback, so this has to be caught here rather than discovered at `add`.
[private]
_contract-drift:
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'

    # A field the distro's project contract has and the home copy does not is a
    # setting the captain cannot make: `extra: forbid` refuses the write and names
    # the key, without saying that the contract is simply older than the field. An
    # upgrade never rewrites a live contract, because a dropped field makes every
    # record still carrying it unreadable, so growing one stays the captain's call
    # and this only makes sure they know there is one to make.
    if [ -f "$home/schema-projects.yaml" ]; then
        absent="$(comm -13 \
            <(grep -oE '^  [a-z_]+:' "$home/schema-projects.yaml" | tr -d ' :' | sort) \
            <(grep -oE '^  [a-z_]+:' "$PWD/template/schema-projects.yaml" | tr -d ' :' | sort))"
        if [ -n "$absent" ]; then
            echo "  stale   schema-projects.yaml is missing: $(echo $absent | tr '\n' ' ')" >&2
            echo "          copy those fields into $home/schema-projects.yaml from" >&2
            echo "          $PWD/template/schema-projects.yaml; until then the registry" >&2
            echo "          refuses to record them" >&2
        fi
    fi

    [ -f "$home/schema-tasks.yaml" ] || exit 0
    fresh="$(mktemp -d)"
    (cd "$fresh" && tasks init >/dev/null 2>&1) || exit 0
    missing="$(comm -13 \
        <(grep -oE '^  [a-z_]+:' "$home/schema-tasks.yaml" | tr -d ' :' | sort) \
        <(grep -oE '^  [a-z_]+:' "$fresh/schema-tasks.yaml" | tr -d ' :' | sort))"
    rm -rf "$fresh"
    [ -z "$missing" ] && exit 0
    echo "  stale   schema-tasks.yaml is missing: $(echo $missing | tr '\n' ' ')" >&2
    echo "          add those fields to $home/schema-tasks.yaml" >&2
    echo "          until then every task the CLI writes is rejected by the" >&2
    echo "          contract, which is a traceback rather than a refusal" >&2

# Build the browser application `siana-console` serves.
#
# `npm ci` and then `vite build`, into `console/dist/`, which is what the console
# reads at startup and what the suite tests. Neither the packages nor the bundle is
# committed: `console/package-lock.json` is what makes the install reproducible, and
# a committed bundle would be a second answer to what the source says.
#
# `just test` runs this first, so an ordinary check builds what it is about to test.
# Run it by hand after a `git pull` that changed the frontend, or after a fresh
# clone: the console serves whatever was last built here and says so on startup when
# there is nothing.
#
# Absent `npm` is reported and not a stop. Nothing else in this distro needs it, and
# a captain who does not want a console should not be told their checkout is broken.
build:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v npm >/dev/null || {
        echo "no npm, so the browser application was not built" >&2
        echo "  it is the only thing here that needs one; siana-console will serve" >&2
        echo "  the API and say that it has no application to serve" >&2
        exit 0
    }
    cd console
    # `npm ci` deletes and reinstalls node_modules every time, which is twenty
    # seconds this recipe pays on every `just test`. It is only needed when what is
    # installed is not what the lockfile says, and npm records that in
    # `node_modules/.package-lock.json`.
    if [ ! -f node_modules/.package-lock.json ] || \
       [ package-lock.json -nt node_modules/.package-lock.json ]; then
        npm ci --no-audit --no-fund
    fi
    npm run build

# Run the distro's tests. Pass unittest arguments through: `just test -v`, or
# `just test -k slug` for one rule.
#
# Through `tests/run.py` rather than `-m unittest` directly, for two reasons.
#
# unittest's own progress is dots with no newline until the summary, and a
# line-oriented reader - the GitHub Actions runner is one - shows none of it. Three
# CI runs on this project were killed by the hang guard having printed nothing at
# all. So: a line per test before it runs, and a watchdog that dumps every thread's
# stack rather than letting a stall eat the job's wall clock in silence.
#
# And the suite is latency-bound rather than CPU-bound - measured at 0.75 of one
# core for its whole length - so it is run across a pool of worker processes. See
# `tests/run.py` for how the pool is sized and why one worker is the control.
#
#     SIANA_TEST_WORKERS=1 just test      unittest, serially, in one process
#
# That is the mode to reach for when a failure looks like it might be the pool's
# fault rather than the code's, and it is the control every timing here is against.
test *args: build
    #!/usr/bin/env bash
    set -euo pipefail
    # No bytecode from this interpreter, and `-B` rather than the suite setting
    # `sys.dont_write_bytecode` on itself: discovery compiles a test module before a
    # line of it runs, so the in-suite guard is already too late for exactly the
    # files that appeared. The flag covers the `bin/` loads in this process too; the
    # guard in tests/helpers.py covers those when the suite is run without `just`.
    #
    # Not exported. PYTHONDONTWRITEBYTECODE would reach the commands the suite drives
    # as processes, which write no bytecode into the worktree anyway: a script run
    # directly never writes its own, and the `bin/` commands import stdlib only. What
    # it does reach is `tasks` and `datafile`, whose uv environments then recompile on
    # every one of the ~464 invocations a run makes, about +92ms each and roughly +40s
    # on a cold runner. Invisible locally, where the captain's uv cache is already
    # warm, and worse than it looks now that a warm run is minutes rather than ten of
    # them: the pool shortens the wall clock and changes none of that cost.
    #
    # The litter is not untidiness. `siana-retire` refuses to remove a worktree
    # holding ignored files, because git deletes those without a word and a `.pyc`
    # and a `.env` look alike to it. That left every minion worktree on this project
    # unretirable until a human cleared a `tests/__pycache__` by hand.
    #
    # `-s tests` and no `-t` so the suite's own helpers import by name. Nothing is
    # installed to run these: they drive the commands where the mechanics are pure,
    # and drive them as processes against a real `tasks` and `datafile` where they
    # are not, because a stubbed store would only ever agree with this suite.
    # `-u` as well as the flushes in `tests/run.py`, so that nothing this recipe
    # runs can hold a line back: the point of the whole arrangement is that what
    # has been printed has really left the process.
    python3 -B -u tests/run.py {{args}}

# Report SIANA's state without changing anything
doctor: _contract-drift
    #!/usr/bin/env bash
    set -uo pipefail
    home='{{home}}'
    echo "home     $home"
    for f in siana.env AGENTS.md orders.md review.md brief-ship.md brief-scout.md brief-qa.md handoff.md principles.md schema-projects.yaml schema-obligations.yaml schema-decisions.yaml schema-tasks.yaml; do
        if [ -e "$home/$f" ]; then echo "  ok      $f"; else echo "  missing $f"; fi
    done
    # An empty queue has no tasks.jsonl at all: datafile creates it on the first
    # append. Absent is the zero, not a fault, and doctor must not cry wolf.
    if [ -e "$home/tasks.jsonl" ]; then echo "  ok      tasks.jsonl"
    elif [ -e "$home/schema-tasks.yaml" ]; then echo "  ok      tasks.jsonl (empty; written on the first task)"
    else echo "  missing tasks.jsonl"; fi
    if [ -e "$home/projects.jsonl" ]; then echo "  ok      projects.jsonl"
    elif [ -e "$home/schema-projects.yaml" ]; then echo "  ok      projects.jsonl (empty; written on the first project)"
    else echo "  missing projects.jsonl"; fi
    if [ -e "$home/obligations.jsonl" ]; then echo "  ok      obligations.jsonl"
    elif [ -e "$home/schema-obligations.yaml" ]; then echo "  ok      obligations.jsonl (empty; written on the first promise)"
    else echo "  missing obligations.jsonl"; fi
    # A home that has never run an advisory session has no ledger at all, which is
    # the zero and not a fault, exactly as the three stores above are.
    if [ -e "$home/decisions.jsonl" ]; then echo "  ok      decisions.jsonl"
    elif [ -e "$home/schema-decisions.yaml" ]; then echo "  ok      decisions.jsonl (empty; written on the first decision)"
    else echo "  missing decisions.jsonl"; fi
    for cmd in tasks datafile; do
        p="$(command -v "$cmd" || true)"
        if [ -n "$p" ]; then echo "  ok      $cmd -> $p"; else echo "  missing $cmd"; fi
    done
    # What `siana-console` runs on, and the only thing here that needs it. Absent is
    # a console this captain cannot start rather than a fault, and it is said in
    # those words: reported as `missing` beside `tasks` it would read as a broken
    # install on every machine that has never wanted a console.
    p="$(command -v node || true)"
    if [ -n "$p" ]; then echo "  ok      node -> $p"
    else echo "  none    node (only siana-console needs it)"; fi
    # The browser application, which is built rather than committed. Absent is a
    # console that serves its API and no page, which is a real thing to be told
    # before the captain opens one on a phone and finds nothing there.
    if [ -f "$PWD/console/dist/index.html" ]; then
        echo "  ok      console app -> $PWD/console/dist"
    else
        echo "  none    console app (run \`just build\`; siana-console serves the API"
        echo "                       and says it has no application to serve)"
    fi
    # What `siana` can start in. A harness needs both the command and the queue
    # integration `init` wrote into this home for it, so they are reported as the
    # one fact they make: a session started with either half missing has no fleet
    # queue in front of it and looks exactly like a working SIANA.
    #
    # pi and claude are alternatives, so an absent one is a harness this captain
    # does not have and never a fault. Only what is here is named; having nothing
    # to start in at all is the stop, and it is the only thing said twice.
    starts=""
    for cmd in pi claude; do
        case "$cmd" in
            pi)     f=".pi/settings.json" ;;
            claude) f=".claude/settings.json" ;;
        esac
        p="$(command -v "$cmd" || true)"
        [ -n "$p" ] || continue
        echo "  ok      $cmd -> $p"
        if [ -e "$home/$f" ]; then
            echo "  ok      $f"
            starts="$starts $cmd"
        else
            echo "  missing $f (\`just init\` writes it)"
        fi
        # The wake consumer, reported only for the harness that has one. It is what
        # delivers `siana-watch`'s wake inside the session without writing into the
        # editor the captain types in, and the watcher refuses to start without it,
        # so a home missing it is one where the fleet cannot advance unattended.
        # Asked only of an installed pi, so its absence is never a fault on a home
        # that has no pi to load it.
        if [ "$cmd" = pi ] && [ -e "$home/$f" ]; then
            if [ -e "$home/.pi/extensions/wake.ts" ]; then
                echo "  ok      .pi/extensions/wake.ts"
            else
                echo "  missing .pi/extensions/wake.ts (\`just init\` writes it;" \
                     "without it \`siana-watch\` refuses to start)"
            fi
            # The queue package the settings file actually configures, counted
            # rather than taken on trust from the file being there. `pi install`
            # only appends, so a home can end up carrying two; pi loads the first
            # and skips the rest, and says so at startup and nowhere else. This
            # report used to call such a home complete, which is how one ran for
            # days reading its queue skill from a package the captain had stopped
            # configuring. Nothing is repaired here - `just init` is what owns the
            # list - so this only has to make the state sayable.
            if ! sources="$(just _pi-packages "$home/.pi/settings.json" 2>&1)"; then
                echo "  stale   .pi/settings.json cannot be read as pi's" \
                     "settings" >&2
                echo "$sources" | sed 's/^/          /' >&2
            else
                # A here-string and not a pipeline, so `queue` survives the loop,
                # and not `for` over the words, so a package path with a space in
                # it is one path.
                queue=""
                while IFS= read -r source; do
                    [ -n "$source" ] \
                        && [ -f "$source/skills/agent-tasks/SKILL.md" ] || continue
                    queue="$queue$source"$'\n'
                done <<< "$sources"
                queue="${queue%$'\n'}"
                count="$(printf '%s' "$queue" | grep -c . || true)"
                if [ "$count" = 1 ]; then
                    echo "  ok      .pi/settings.json queue package"
                elif [ "$count" = 0 ]; then
                    echo "  missing a queue package in .pi/settings.json" \
                         "(\`just init\` installs one; without it a pi" \
                         "session opens with no queue in front of it)"
                else
                    echo "  stale   .pi/settings.json configures $count queue" \
                         "packages, and pi loads only the first" >&2
                    echo "$queue" | sed 's/^/          /' >&2
                    echo "          \`just init\` installs one instead of adding" \
                         "to the list; run it to" >&2
                    echo "          keep the package it is configured for" >&2
                fi
            fi
        fi
    done
    if [ -n "$starts" ]; then
        # Which one is the default only means anything when there is a choice, and
        # a home with one harness reading "the first is the default" invites the
        # captain to go looking for the second.
        case "$starts" in
            *" "*" "*) echo "  ok      siana starts in:$starts (the first by default)" ;;
            *)         echo "  ok      siana starts in:$starts" ;;
        esac
    else
        echo "  no harness to start in; install pi or claude, then \`just init\`" >&2
    fi
    # One SIANA leads the fleet, so which one is a thing the captain can ask about.
    # No session is the ordinary state between sessions and never a fault; a session
    # whose pid is gone is one killed before its trap ran, and blocks the next start.
    pid="$(sed -n 's/^SIANA_PID=//p' "$home/session" 2>/dev/null)"
    pane="$(sed -n 's/^SIANA_PANE=//p' "$home/session" 2>/dev/null)"
    if [ -z "$pid" ]; then
        echo "  ok      no SIANA running"
    elif ! kill -0 "$pid" 2>/dev/null; then
        echo "  stale   session claims pid $pid, which is gone" >&2
        echo "          remove $home/session to start a new SIANA" >&2
    else
        echo "  ok      SIANA running (pid $pid${pane:+, pane $pane})"
    fi
    # Whether the fleet advances while the captain is away. The watcher owns its own
    # record, so it is asked rather than parsed here: a file can say a watcher was
    # started and never that one is running, and only the command that wrote it knows
    # how to tell those apart. It reports and never repairs, because removing a
    # stopped watcher's record is deciding the captain has read it.
    SIANA_HOME="$home" "$PWD/bin/siana-watch" --status || true
    # Whether SIANA is writing down decisions instead of asking. Asked of the command
    # that wrote the record for the reason the watcher is: a file can say a session
    # was started and never that one is running, and only the command that wrote it
    # knows how to tell those apart. It reports and never repairs.
    SIANA_HOME="$home" "$PWD/bin/siana-afk" --status || true
    # Dispatch does the resolving and holds the pane bindings, so asking it means
    # this cannot drift from what a real dispatch would accept or from where a real
    # minion was put. It reports a dead owner and never reclaims one: `tasks reset`
    # stays manual because a dead minion's worktree may hold unlanded work.
    echo
    SIANA_HOME="$home" "$PWD/bin/siana-dispatch" --check || true
    echo
    SIANA_HOME="$home" "$PWD/bin/siana-owe" || true
    echo
    [ -d "$home" ] && (cd "$home" && tasks)

# Remove the installed commands. SIANA's home and its queue are left alone.
uninstall:
    #!/usr/bin/env bash
    set -euo pipefail
    for c in siana siana-dispatch siana-brief siana-watch siana-owe siana-retire siana-handoff siana-publish siana-reap siana-pipeline siana-afk siana-gate siana-read siana-console; do
        link="{{bindir}}/$c"
        if [ ! -L "$link" ] && [ ! -e "$link" ]; then
            echo "not installed: $link"
        elif [ "$(readlink "$link" || true)" = "$PWD/bin/$c" ]; then
            rm "$link"
            echo "removed $link"
        else
            echo "refusing to remove $link: not a link to $PWD/bin/$c" >&2
            exit 1
        fi
    done
    echo "kept    {{home}} (delete it by hand; it holds the queue)"
