"""The recipes the captain actually runs: `init`, `upgrade`, `doctor`.

`init` is exercised for real, into a throwaway home with a throwaway bindir, because
the thing worth checking is that a fresh install is one the rest of the distro can
read. The two refusals under it are the ones that turn a typo into a fresh empty
fleet, or a stale contract into a traceback at `add` time.
"""

import json
import os
import shutil
import subprocess
import tempfile
import unittest

from helpers import DISTRO, HomeTest, gone_pid, script

w = script("siana-watch")


def has(cmd):
    return shutil.which(cmd) is not None


class Recipe(HomeTest):

    def setUp(self):
        super().setUp()
        self.bindir = self.at("bin")

    def just(self, *args, home=None, pi_package="", env=None, timeout=180):
        e = dict(os.environ)
        # Every location the recipes write to is passed as a just variable, and the
        # environment that would override one is dropped: a suite that inherited the
        # captain's SIANA_HOME or SIANA_PI_PACKAGE would install over the live fleet.
        e.pop("SIANA_HOME", None)
        e.pop("SIANA_PI_PACKAGE", None)
        # `doctor` asks `siana-dispatch --check`, which prefers SIANA_TASKS_FILE
        # over the home it was given. Inherited, that reads the live fleet's queue,
        # and these assertions would be about whatever the captain has in flight.
        e.pop("SIANA_TASKS_FILE", None)
        e.update(env or {})
        variables = [f"home={home if home is not None else self.home}",
                     f"bindir={self.bindir}"]
        # The just variable wins over the environment, so `pi_package=None` is how a
        # test of the SIANA_PI_PACKAGE route leaves it off entirely. Passing an
        # empty one instead would silently pin the variable and test nothing.
        if pi_package is not None:
            variables.append(f"pi_package={pi_package}")
        return subprocess.run(["just", *variables, *args],
            cwd=DISTRO, env=e, text=True, capture_output=True, timeout=timeout)


    def stub(self, *names):
        """Commands that exist and are never run, in a directory to put on PATH.

        `init` only asks whether a harness is installed: what writes the queue
        integration for one is `tasks`, never the harness itself. So a stub is the
        whole of what init needs to find, and the claude paths below are exercised
        on a machine that has no Claude Code - CI, for one."""
        d = self.at("stub")
        os.makedirs(d, exist_ok=True)
        for name in names:
            path = os.path.join(d, name)
            with open(path, "w") as fh:
                fh.write("#!/bin/sh\nexit 0\n")
            os.chmod(path, 0o755)
        return d

    def on_path(self, first, rest=None):
        return os.pathsep.join([first, rest if rest is not None
                                else os.environ["PATH"]])

    def package(self, *parts):
        """A real pi package, generated by the installed `tasks`. Generated rather
        than mocked up here: what makes a directory a package is `tasks`' business,
        and a hand-built stand-in would only agree with this suite's guess at it."""
        path = self.at(*parts)
        out = subprocess.run(["tasks", "pi-package", "--out", path],
                             text=True, capture_output=True, timeout=60)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        return path


class Upgrade(Recipe):

    def test_upgrading_a_home_that_was_never_created_is_refused(self):
        # `init` would happily build one, so a typo in SIANA_HOME would read as a
        # successful upgrade of a fleet that has nothing in it.
        missing = self.at("never-created")
        self.assertRefused(self.just("upgrade", home=missing),
                           "no SIANA home at", "just init")
        self.assertFalse(os.path.exists(missing))


class ContractDrift(Recipe):
    """A field the CLI writes and the home's contract lacks is refused by
    `extra: forbid` as a raw traceback, so it has to be caught before `add`."""

    def test_a_project_contract_missing_a_field_is_named_as_stale(self):
        self.contract("projects")
        with open(self.at("schema-projects.yaml")) as fh:
            text = fh.read()
        # Drop `qa`, the way a home written before that field looks.
        cut = text.split("  qa:")[0] + text.split("      behind every ship task in this project\n")[1]
        with open(self.at("schema-projects.yaml"), "w") as fh:
            fh.write(cut)
        out = self.just("doctor")
        self.assertIn("stale   schema-projects.yaml is missing: qa", out.stderr)
        self.assertIn("refuses to record them", out.stderr)

    def test_a_current_project_contract_is_not_called_stale(self):
        self.contract("projects")
        self.assertNotIn("schema-projects.yaml is missing", self.just("doctor").stderr)


class Doctor(Recipe):

    def watcher(self, **fields):
        """A watcher status record, written the way the watcher writes one."""
        with open(self.at(w.GRANT), "w") as fh:
            json.dump(fields, fh)
        return self.at(w.GRANT)

    def test_it_names_what_is_missing_from_an_empty_home(self):
        out = self.just("doctor")
        self.assertIn("missing AGENTS.md", out.stdout)
        self.assertIn("missing orders.md", out.stdout)

    def test_an_empty_store_is_a_zero_and_never_a_fault(self):
        # datafile writes the .jsonl on the first append, so absent-with-a-contract
        # is an empty store. Doctor must not cry wolf about it.
        self.contract("projects", "obligations", "decisions")
        out = self.just("doctor").stdout
        self.assertIn("projects.jsonl (empty; written on the first project)", out)
        self.assertIn("obligations.jsonl (empty; written on the first promise)", out)
        # A home that has never run an advisory session has no ledger at all, which
        # is the same zero and not a home missing part of its install.
        self.assertIn("decisions.jsonl (empty; written on the first decision)", out)

    def test_no_siana_running_is_the_ordinary_state(self):
        self.assertIn("no SIANA running", self.just("doctor").stdout)

    def test_a_session_whose_process_is_gone_is_called_stale(self):
        with open(self.at("session"), "w") as fh:
            fh.write(f"SIANA_PID={gone_pid()}\n")
        out = self.just("doctor")
        self.assertIn("stale   session claims pid", out.stderr)

    def test_no_watcher_is_said_out_loud_rather_than_left_to_be_assumed(self):
        # The state the whole record exists for. A quiet fleet and a stopped watcher
        # look identical, so silence here would be the captain assuming coverage.
        out = self.just("doctor")
        self.assertIn("no watcher (the fleet does not advance unattended)", out.stdout)

    def test_a_watcher_whose_process_is_running_is_reported_as_running(self):
        # This test's own process, because that is the only one here that is
        # certainly alive: the record is evidence about a process, and doctor asks
        # the operating system about it rather than believing the file.
        self.watcher(state="running", pid=os.getpid(),
                     command=w.process_command(os.getpid()), pane="w1:p1",
                     started="2026-08-28T08:00:00Z")
        out = self.just("doctor")
        self.assertIn(f"ok      watcher running (pid {os.getpid()}", out.stdout)
        self.assertNotIn("watcher", out.stderr)

    def test_a_watcher_that_stopped_is_named_with_its_reason_and_what_to_do(self):
        self.watcher(state="failed", pid=gone_pid(), command="/usr/bin/whatever",
                     pane="w1:p1", started="2026-08-28T08:00:00Z",
                     stopped="2026-08-28T09:00:00Z",
                     reason="pane w1:p1 is not running SIANA: herdr sees claude")
        out = self.just("doctor")
        self.assertIn("stale   watcher stopped at", out.stderr)
        self.assertIn("herdr sees claude", out.stderr)
        self.assertIn("start `siana-watch`", out.stderr)

    def test_a_watcher_that_died_without_saying_why_is_never_reported_healthy(self):
        self.watcher(state="running", pid=gone_pid(), command="/usr/bin/whatever",
                     pane="w1:p1", started="2026-08-28T08:00:00Z")
        out = self.just("doctor")
        self.assertIn("stale   watcher stopped without saying why", out.stderr)
        self.assertNotIn("watcher running", out.stdout)

    def test_a_stopped_watchers_record_is_reported_and_never_repaired(self):
        # Removing it is deciding the captain has read it, and doctor changes
        # nothing.
        path = self.watcher(state="failed", pid=gone_pid(), command="x",
                            reason="herdr went away")
        self.just("doctor")
        self.assertTrue(os.path.exists(path))

    def test_no_advisory_session_is_reported_as_ok(self):
        # The state the fleet is in whenever the captain is at the helm, and the
        # state it is in most of the time. Reported the way `no watcher` is: an
        # absence that is ordinary, said out loud rather than left to be assumed.
        out = self.just("doctor")
        self.assertIn("no advisory session (every decision is the captain's)",
                      out.stdout)
        self.assertNotIn("advisory", out.stderr)

    def test_a_session_whose_process_is_gone_is_never_reported_healthy(self):
        # Every gate call has been refusing since that process died, so a captain
        # reading a healthy line here would be reading the opposite of the truth.
        with open(self.at("afk"), "w") as fh:
            json.dump({"state": "running", "pid": gone_pid(),
                       "command": "python3 /somewhere/bin/siana-afk",
                       "started": "2026-08-29T20:00:00Z",
                       "until": "2099-01-01T00:00:00Z", "allow": [],
                       "projects": ["demo"]}, fh)
        out = self.just("doctor")
        self.assertIn("advisory session stopped without saying why", out.stderr)
        self.assertNotIn("advisory session running", out.stdout)

    def test_a_stopped_advisory_sessions_record_is_reported_and_never_repaired(self):
        with open(self.at("afk"), "w") as fh:
            json.dump({"state": "running", "pid": gone_pid(), "command": "siana-afk",
                       "started": "2026-08-29T20:00:00Z",
                       "until": "2099-01-01T00:00:00Z", "allow": [],
                       "projects": ["demo"]}, fh)
        self.just("doctor")
        self.assertTrue(os.path.exists(self.at("afk")))

    @unittest.skipUnless(has("pi"), "the package is reported for pi only")
    def test_a_pi_home_with_no_settings_at_all_is_never_reported_healthy(self):
        # The case the package check exists for, arriving one layer up. With no
        # settings file there is nothing for the check to read, so it is never
        # reached - and a home that names no pi-siana package at all exited 0 while
        # a home that named it badly exited 1.
        out = self.just("doctor")
        self.assertNotEqual(out.returncode, 0, out.stdout)
        self.assertIn("missing .pi/settings.json", out.stdout)

    @unittest.skipUnless(has("pi"), "the wake extension is reported for pi only")
    def test_a_pi_home_without_the_wake_extension_is_named_as_missing(self):
        # The watcher refuses to start without it, so a home missing it is one where
        # the fleet cannot advance unattended - and the captain would otherwise only
        # find that out at the moment they walked away.
        os.makedirs(self.at(".pi"), exist_ok=True)
        with open(self.at(".pi", "settings.json"), "w") as fh:
            fh.write("{}\n")
        out = self.just("doctor").stdout
        self.assertIn("missing .pi/extensions/wake.ts", out)
        self.assertIn("`siana-watch` refuses to start", out)


class Suite(unittest.TestCase):
    """The one flag in `just test` whose cost is paid outside the suite."""

    def recipe(self):
        with open(os.path.join(DISTRO, "justfile")) as fh:
            lines = fh.read().splitlines()
        start = next(i for i, line in enumerate(lines)
                     if line.startswith("test *args:"))
        body = []
        for line in lines[start + 1:]:
            if line and not line[0].isspace():
                break
            body.append(line)
        return body

    def test_the_suite_writes_no_bytecode(self):
        # Without `-B`, discovery compiles every test module into a `__pycache__`
        # inside whatever worktree the suite ran in. `siana-retire` refuses to remove
        # a tree holding ignored files, because git deletes those without a word and
        # a `.pyc` and a `.env` look alike to it, so that litter made every minion
        # worktree on this project unretirable until a human cleared it by hand. The
        # flag is one word and the failure it prevents is a manual step on every
        # task, so it is checked rather than remembered.
        runs = [line.strip() for line in self.recipe()
                if line.strip().startswith("python3")]
        self.assertTrue(runs, "the `test` recipe no longer runs python3")
        for line in runs:
            self.assertIn(" -B ", line,
                          f"`{line}` writes bytecode into the worktree it runs in")


@unittest.skipUnless(has("pi") and has("tasks") and has("datafile"),
                     "init needs pi, tasks and datafile")
class Init(Recipe):
    """A real install into a throwaway home."""

    def test_a_fresh_home_is_one_the_rest_of_the_distro_can_read(self):
        out = self.just("init")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        for f in ("siana.env", "AGENTS.md", "orders.md", "review.md",
                  "brief-ship.md", "brief-scout.md", "brief-qa.md",
                  # The document a ship minion writes the merge request in. Without
                  # it `siana-handoff --scaffold` has nothing to lay down, and a
                  # minion writing the shape from memory is where format drift
                  # starts.
                  "handoff.md",
                  "schema-projects.yaml", "schema-obligations.yaml",
                  "schema-decisions.yaml", "schema-tasks.yaml",
                  # The reasoning behind the decisions the captain was asked. A
                  # decision recorded without it is one nothing can learn from, and
                  # `siana-owe decision` refuses rather than writing one.
                  "schema-attended.yaml",
                  # What a cleanup run reads before it starts. Written here so that
                  # `doctor` can say whether it is there, rather than a cleaner
                  # having to create the file it reads.
                  "runbook.md",
                  # The principles an advisory session holds SIANA to. It ships
                  # unfilled and `siana-afk` refuses to start until it is written,
                  # so a home without it is one where a session cannot start at all.
                  "principles.md",
                  # The wake consumer. Without it `siana-watch` refuses to start,
                  # so a home it was left out of is a home that cannot advance the
                  # fleet unattended.
                  os.path.join(".pi", "extensions", "wake.ts")):
            self.assertTrue(os.path.exists(self.at(f)), f"init left out {f}")
        for c in ("siana", "siana-dispatch", "siana-brief", "siana-watch",
                  "siana-owe", "siana-retire", "siana-handoff", "siana-publish",
                  "siana-reap", "siana-pipeline", "siana-afk", "siana-gate",
                  "siana-clean", "siana-report"):
            link = os.path.join(self.bindir, c)
            self.assertTrue(os.path.islink(link), f"{c} was not linked")
            # realpath both sides: what matters is that the link lands on this
            # distro's command, not how the path to it happens to be spelled. A
            # checkout under a symlinked prefix spells it two ways.
            self.assertEqual(os.path.realpath(link),
                             os.path.realpath(os.path.join(DISTRO, "bin", c)))
        doctor = self.just("doctor")
        self.assertNotIn("stale", doctor.stderr)
        # Nothing is tolerated here. The ambient queue used to depend on a tasks
        # checkout beside this one, so this had to excuse a missing
        # `.pi/settings.json` from a worktree - which meant the assertion was about
        # where the suite was checked out rather than about the install. `init`
        # generates the package from the installed `tasks` now, so a complete home
        # is complete everywhere.
        missing = [line.strip() for line in doctor.stdout.splitlines()
                   if "missing " in line]
        self.assertEqual(missing, [])

    def siana_package_entries(self):
        """Every settings entry that resolves to this distro's pi package.

        Resolved rather than compared as strings: pi writes the entry relative to the
        settings file, and the whole failure this guards against is one package
        reached through two spellings.
        """
        settings = self.at(".pi", "settings.json")
        with open(settings) as fh:
            packages = json.load(fh).get("packages", [])
        want = os.path.realpath(os.path.join(DISTRO, "template", "pi-siana"))
        out = []
        for entry in packages:
            source = entry if isinstance(entry, str) else entry.get("source", "")
            resolved = os.path.realpath(
                os.path.join(os.path.dirname(settings), source))
            if resolved == want:
                out.append(source)
        return out

    def test_the_distros_own_package_is_installed_exactly_once(self):
        self.assertEqual(self.just("init").returncode, 0)
        self.assertEqual(len(self.siana_package_entries()), 1)

    def test_a_second_init_does_not_install_it_twice(self):
        self.assertEqual(self.just("init").returncode, 0)
        self.assertEqual(self.just("init").returncode, 0)
        self.assertEqual(len(self.siana_package_entries()), 1)

    def test_the_same_package_under_a_second_spelling_is_reconciled_away(self):
        # The collision this exists to prevent. Pi identifies a local package by its
        # resolved absolute path, so a relative entry and an absolute one naming the
        # same directory are two packages: two `/captain-report` commands, two
        # `siana_cleanup` tools, and a skill-name collision at every startup.
        self.assertEqual(self.just("init").returncode, 0)
        settings = self.at(".pi", "settings.json")
        with open(settings) as fh:
            config = json.load(fh)
        config["packages"].append(
            os.path.realpath(os.path.join(DISTRO, "template", "pi-siana")))
        with open(settings, "w") as fh:
            json.dump(config, fh)
        self.assertEqual(len(self.siana_package_entries()), 2)
        self.assertEqual(self.just("init").returncode, 0)
        self.assertEqual(len(self.siana_package_entries()), 1)

    def test_reconciling_leaves_the_queue_package_alone(self):
        # It is another local entry in the same array, and losing it would take the
        # ambient queue out of SIANA's session while looking like a clean install.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at(".pi", "settings.json")) as fh:
            packages = json.load(fh)["packages"]
        self.assertTrue(any("pi-agent-tasks" in str(p) for p in packages), packages)

    def test_the_package_extension_is_not_also_auto_discovered(self):
        # An extension present in `.pi/extensions/` *and* in an installed package is
        # loaded twice, which is the same collision by another route.
        self.assertEqual(self.just("init").returncode, 0)
        self.assertEqual(sorted(os.listdir(self.at(".pi", "extensions"))),
                         ["wake.ts"])

    def settings(self, mutate):
        """The home's pi settings, rewritten by `mutate`. Every check below is about
        what doctor makes of the file rather than about how it got that way, so the
        home is installed for real first and then damaged."""
        path = self.at(".pi", "settings.json")
        with open(path) as fh:
            config = json.load(fh)
        mutate(config)
        with open(path, "w") as fh:
            json.dump(config, fh)

    def test_doctor_passes_the_package_the_install_actually_wrote(self):
        # The half that makes every refusal below mean something. A check nothing
        # can satisfy would fail an install that is correct.
        self.assertEqual(self.just("init").returncode, 0)
        doctor = self.just("doctor")
        self.assertEqual(doctor.returncode, 0, doctor.stdout + doctor.stderr)
        self.assertIn("ok      .pi/settings.json (pi-siana)", doctor.stdout)

    def test_a_home_that_lost_the_package_is_never_reported_healthy(self):
        # The gap this closes. Doctor checked that `.pi/settings.json` existed, and
        # a home whose packages array had lost the pi-siana entry has no
        # `siana_cleanup` and no `siana_runbook` tool, no `captain-report` skill and
        # no `/captain-report` command - none of which fails, because none of them
        # is there to be called. It printed `ok .pi/settings.json` and exited 0.
        self.assertEqual(self.just("init").returncode, 0)
        self.settings(lambda config: config.__setitem__(
            "packages", [p for p in config["packages"]
                         if "pi-siana" not in str(p)]))
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("missing pi-siana package: no entry names it", doctor.stderr)
        self.assertIn("`just init` installs it", doctor.stderr)

    def test_a_second_spelling_of_the_package_is_reported_rather_than_blessed(self):
        # Two spellings of one directory are two packages to pi, so every resource
        # in it is discovered twice. `init` reconciles it; doctor is what says the
        # captain needs to run one.
        self.assertEqual(self.just("init").returncode, 0)
        self.settings(lambda config: config["packages"].append(
            os.path.realpath(os.path.join(DISTRO, "template", "pi-siana"))))
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("2 entries name it", doctor.stderr)
        self.assertIn("`just init` installs it", doctor.stderr)

    def test_an_entry_that_resolves_nowhere_is_not_a_present_package(self):
        # The failure the README already names: the entry is a relative path into
        # the checkout, so a checkout that moved leaves a settings file that still
        # names a package and a home that has none.
        self.assertEqual(self.just("init").returncode, 0)
        self.settings(lambda config: config.__setitem__(
            "packages", [p for p in config["packages"]
                         if "pi-siana" not in str(p)]
            + [os.path.join(self.home, "moved-away", "pi-siana")]))
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("which is not there", doctor.stderr)

    def test_a_directory_that_is_no_package_is_not_a_present_package(self):
        # The near miss `init` already refuses on the way in, asked of a home that
        # has one anyway. Existing and a directory is not enough.
        self.assertEqual(self.just("init").returncode, 0)
        empty = self.at("empty", "pi-siana")
        os.makedirs(empty, exist_ok=True)
        self.settings(lambda config: config.__setitem__(
            "packages", [p for p in config["packages"]
                         if "pi-siana" not in str(p)] + [empty]))
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("holds no package.json", doctor.stderr)

    def test_settings_that_are_json_but_hold_no_object_are_told_apart(self):
        # `null` parses without error, so the parse guard passes it straight
        # through, and the check then had nothing to ask about and no answer
        # assigned: it raised a NameError and printed a traceback where the reason
        # and the repair belong. Doctor still failed, which is why this is a report
        # defect and not a safety one - and it is the same tracing-instead-of-
        # refusing this branch has already fixed twice elsewhere.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at(".pi", "settings.json"), "w") as fh:
            fh.write("null\n")
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("does not hold a JSON object", doctor.stderr)
        self.assertIn("`just init` installs it", doctor.stderr)
        self.assertNotIn("Traceback", doctor.stderr)

    def test_settings_that_will_not_parse_is_never_a_healthy_package(self):
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at(".pi", "settings.json"), "w") as fh:
            fh.write("{ this is not json\n")
        doctor = self.just("doctor")
        self.assertNotEqual(doctor.returncode, 0, doctor.stdout)
        self.assertIn("will not parse", doctor.stderr)
        self.assertIn("`just init` installs it", doctor.stderr)

    def test_doctor_reports_the_runbook_and_the_cleanup_state(self):
        self.assertEqual(self.just("init").returncode, 0)
        doctor = self.just("doctor")
        self.assertIn("runbook.md", doctor.stdout)
        self.assertIn("attended.jsonl", doctor.stdout)
        # A home that has never run one is a zero and not a fault.
        self.assertIn("cleanup  no runs", doctor.stdout)

    def test_upgrade_keeps_the_runbook_and_the_attended_contract(self):
        # Both hold the fleet's own accumulated answers. An upgrade that rewrote
        # either would lose them to restore something nobody needed.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("runbook.md"), "a") as fh:
            fh.write("\n<!-- siana-clean:q1 -->\n## Is it?\n\nNo.\n")
        out = self.just("upgrade")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        with open(self.at("runbook.md")) as fh:
            self.assertIn("No.", fh.read())
        self.assertIn("kept     ", out.stdout)
        self.assertIn("schema-attended.yaml", out.stdout)

    def test_the_wake_extension_is_the_distros_and_is_refreshed_on_every_init(self):
        # Distro-owned and never the captain's work, so it is overwritten rather
        # than kept: an old copy is an extension that does not match the watcher
        # shipping beside it. This is also what an upgrade relies on, since
        # `upgrade` reaches this by depending on `init`.
        self.assertEqual(self.just("init").returncode, 0)
        installed = self.at(".pi", "extensions", "wake.ts")
        with open(installed, "w") as fh:
            fh.write("// a copy from an older distro\n")
        again = self.just("init")
        self.assertEqual(again.returncode, 0, again.stdout + again.stderr)
        with open(installed) as fh:
            copy = fh.read()
        with open(os.path.join(DISTRO, "template", "wake.ts")) as fh:
            self.assertEqual(copy, fh.read())
        # And never inside the tasks package, which `init` regenerates from
        # scratch: anything put there is gone on the next install.
        self.assertFalse(os.path.exists(
            self.at("pi-agent-tasks", "extensions", "wake.ts")))

    def test_the_claude_queue_integration_is_installed_beside_the_pi_one(self):
        # Both halves, because the pi package carries both and a home that gains
        # only the skill opens a session that has to remember to go and ask - which
        # is the thing an ambient queue replaces.
        path = self.on_path(self.stub("claude"), rest=self.path_without("claude"))
        out = self.just("init", env={"PATH": path})
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertTrue(os.path.exists(self.at(".claude", "settings.json")))
        self.assertTrue(os.path.exists(
            self.at(".claude", "skills", "agent-tasks", "SKILL.md")))
        # And pi's, unchanged: installing for one harness never costs the other.
        self.assertTrue(os.path.exists(self.at(".pi", "settings.json")))

    def test_a_machine_with_claude_and_no_pi_is_installed_for_claude(self):
        # It used to be refused outright. What it must not become instead is a
        # half-install: a pi package generated for a pi that is not there, or a
        # home `doctor` calls complete with nothing to start a session in.
        path = self.on_path(self.stub("claude"),
                            rest=self.path_without("pi", "claude"))
        out = self.just("init", env={"PATH": path})
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertTrue(os.path.exists(self.at(".claude", "settings.json")))
        # No pi, so no pi extension either. The watcher refuses a claude SIANA
        # outright, and an extension nothing could load would only read as one more
        # thing to go looking for.
        self.assertFalse(os.path.exists(self.at(".pi")))
        self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))
        doctor = self.just("doctor", env={"PATH": path})
        self.assertIn("siana starts in: claude", doctor.stdout)
        # Nothing is tolerated: a claude-only home is a complete home, and doctor
        # calling pi's absence a fault would send the captain installing it.
        missing = [line.strip() for line in doctor.stdout.splitlines()
                   if "missing " in line]
        self.assertEqual(missing, [])

    def test_a_machine_with_neither_harness_is_refused_before_anything_is_written(self):
        # `siana` refuses to start in a home with no queue integration, so an
        # install that wrote none at all is a home the captain would only find out
        # about at the helm.
        out = self.just("init", env={"PATH": self.path_without("pi", "claude")})
        self.assertRefused(out, "missing: pi and claude", "install at least one")
        self.assertFalse(os.path.exists(self.at("siana.env")))

    def test_a_pi_package_named_with_no_pi_to_install_it_into_is_refused(self):
        # Not skipped as harmless. The captain who set it is expecting a pi
        # session, and an init that quietly wrote a claude home instead would be
        # answering a question they did not ask.
        pkg = self.package("elsewhere", "pi-agent-tasks")
        path = self.on_path(self.stub("claude"),
                            rest=self.path_without("pi", "claude"))
        self.assertRefused(self.just("init", pi_package=pkg, env={"PATH": path}),
                           "SIANA_PI_PACKAGE is set and pi is not installed")
        self.assertFalse(os.path.exists(self.at("siana.env")))

    def test_a_configured_pi_package_is_the_one_installed(self):
        # The captain who keeps their own package - a tasks checkout they are
        # editing - gets that one, not a generated copy that would shadow it.
        pkg = self.package("elsewhere", "pi-agent-tasks")
        out = self.just("init", pi_package=pkg)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertTrue(os.path.exists(self.at(".pi", "settings.json")))
        # And nothing was generated beside it, which is how a silent fallback to a
        # different package would show.
        self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_configured_pi_package_is_the_one_installed_through_the_environment(self):
        # The route the README documents, and the one the just variable shadows:
        # passing the variable at all would make this test the other one again.
        # Twice, because an install the captain repeats has to stay the one they
        # asked for rather than drift to a generated package on the second run.
        pkg = self.package("own-package")
        for _ in range(2):
            out = self.just("init", pi_package=None,
                            env={"SIANA_PI_PACKAGE": pkg})
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            with open(self.at(".pi", "settings.json")) as fh:
                self.assertIn("own-package", fh.read())
            self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_configured_pi_package_that_is_absent_is_refused(self):
        # Never a fallback: generating a different package behind the captain's
        # back gives SIANA a queue skill that is not the one they pointed at. And
        # the refusal comes before anything is written, so a typo costs a retype.
        gone = os.path.join(self.home, "not-a-package")
        self.assertRefused(self.just("init", pi_package=gone),
                           "no pi package directory at", "SIANA_PI_PACKAGE")
        self.assertFalse(os.path.exists(self.at("siana.env")))

    def test_a_configured_directory_that_is_no_package_is_refused(self):
        # The near miss, and the one that used to get through: a tasks checkout
        # root rather than the `pi-agent-tasks` package inside it. `pi install`
        # accepts any directory, so init exited 0 with a settings.json naming a
        # directory holding no package - a home `doctor` called complete with no
        # queue in front of SIANA. Existing and a directory is not enough.
        checkout = os.path.join(self.home, "checkout")
        self.package(os.path.join("checkout", "pi-agent-tasks"))
        self.assertRefused(self.just("init", pi_package=checkout),
                           "not a pi package", "no package.json in", "SIANA_PI_PACKAGE")
        # Nothing was written, and above all no settings.json naming it: a home
        # that half exists is recoverable, one that looks installed is not.
        self.assertFalse(os.path.exists(self.at("siana.env")))
        self.assertFalse(os.path.exists(self.at(".pi", "settings.json")))
        self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_directory_that_is_no_package_is_refused_through_the_environment(self):
        checkout = os.path.join(self.home, "checkout")
        self.package(os.path.join("checkout", "pi-agent-tasks"))
        self.assertRefused(
            self.just("init", pi_package=None, env={"SIANA_PI_PACKAGE": checkout}),
            "not a pi package", "no package.json in")
        self.assertFalse(os.path.exists(self.at(".pi", "settings.json")))

    def test_it_is_idempotent_and_never_clobbers_an_evolved_file(self):
        # SIANA can evolve its own instructions, so a diverged home copy is the
        # captain's work and not drift to be cleaned up.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("AGENTS.md"), "a") as fh:
            fh.write("\nThe captain prefers reports at noon.\n")
        again = self.just("init")
        self.assertEqual(again.returncode, 0, again.stdout + again.stderr)
        self.assertIn("kept     ", again.stdout)
        with open(self.at("AGENTS.md")) as fh:
            self.assertIn("reports at noon", fh.read())

    def test_neither_init_nor_upgrade_ever_rewrites_the_principles(self):
        # Harder than the instructions, which `upgrade` replaces with a diff beside
        # them. This is the only file an advisory session lets SIANA read a principle
        # from, so a distro that could rewrite it could rewrite what SIANA is held to
        # while the captain is asleep.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("principles.md"), "w") as fh:
            fh.write("# Principles\n\nNever publish on a Friday.\n")
        for recipe in ("init", "upgrade"):
            out = self.just(recipe)
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            self.assertIn("kept     ", out.stdout)
            with open(self.at("principles.md")) as fh:
                self.assertIn("Never publish on a Friday", fh.read())
        # And no backup of it was left anywhere under upgrade/, because nothing was
        # replaced to need one. Walked rather than guessed at, since the backup
        # directory is stamped with the time the upgrade ran.
        backups = []
        for root, _, files in os.walk(self.at("upgrade")):
            backups += files
        self.assertNotIn("principles.md", backups)

    def test_uninstall_removes_the_links_and_leaves_the_home_alone(self):
        self.assertEqual(self.just("init").returncode, 0)
        out = self.just("uninstall")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.bindir, "siana")))
        self.assertTrue(os.path.exists(self.at("tasks.jsonl")) or
                        os.path.exists(self.at("schema-tasks.yaml")))
        self.assertIn("kept    ", out.stdout)

    def test_uninstall_refuses_to_remove_something_it_did_not_install(self):
        os.makedirs(self.bindir, exist_ok=True)
        with open(os.path.join(self.bindir, "siana"), "w") as fh:
            fh.write("#!/bin/sh\n")
        self.assertRefused(self.just("uninstall"), "refusing to remove")
        self.assertTrue(os.path.exists(os.path.join(self.bindir, "siana")))

    def test_upgrade_preserves_an_evolved_file_with_the_diff_beside_it(self):
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("orders.md"), "w") as fh:
            fh.write("# My own orders\n")
        out = self.just("upgrade")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertIn("upgraded ", out.stdout)
        backups = []
        for root, _, files in os.walk(self.at("upgrade")):
            backups += [os.path.join(root, f) for f in files]
        kept = [b for b in backups if b.endswith("orders.md")]
        diffs = [b for b in backups if b.endswith("orders.md.diff")]
        self.assertTrue(kept, f"the captain's copy was not preserved: {backups}")
        self.assertTrue(diffs, f"no diff was left beside it: {backups}")
        with open(kept[0]) as fh:
            self.assertIn("My own orders", fh.read())
        with open(self.at("orders.md")) as fh:
            self.assertIn("Standing orders", fh.read())


if __name__ == "__main__":
    unittest.main()
