"""The recipes the captain actually runs: `init`, `upgrade`, `doctor`.

`init` is exercised for real, into a throwaway home with a throwaway bindir, because
the thing worth checking is that a fresh install is one the rest of the distro can
read. The two refusals under it are the ones that turn a typo into a fresh empty
fleet, or a stale contract into a traceback at `add` time.
"""

import json
import os
import shutil
import subprocess
import tempfile
import unittest

from helpers import DISTRO, HomeTest, gone_pid, script

w = script("siana-watch")


def has(cmd):
    return shutil.which(cmd) is not None


class Recipe(HomeTest):

    def setUp(self):
        super().setUp()
        self.bindir = self.at("bin")

    def just(self, *args, home=None, pi_package="", env=None, timeout=180):
        e = dict(os.environ)
        # Every location the recipes write to is passed as a just variable, and the
        # environment that would override one is dropped: a suite that inherited the
        # captain's SIANA_HOME or SIANA_PI_PACKAGE would install over the live fleet.
        e.pop("SIANA_HOME", None)
        e.pop("SIANA_PI_PACKAGE", None)
        # `doctor` asks `siana-dispatch --check`, which prefers SIANA_TASKS_FILE
        # over the home it was given. Inherited, that reads the live fleet's queue,
        # and these assertions would be about whatever the captain has in flight.
        e.pop("SIANA_TASKS_FILE", None)
        e.update(env or {})
        variables = [f"home={home if home is not None else self.home}",
                     f"bindir={self.bindir}"]
        # The just variable wins over the environment, so `pi_package=None` is how a
        # test of the SIANA_PI_PACKAGE route leaves it off entirely. Passing an
        # empty one instead would silently pin the variable and test nothing.
        if pi_package is not None:
            variables.append(f"pi_package={pi_package}")
        return subprocess.run(["just", *variables, *args],
            cwd=DISTRO, env=e, text=True, capture_output=True, timeout=timeout)


    def package(self, *parts):
        """A real pi package, generated by the installed `tasks`. Generated rather
        than mocked up here: what makes a directory a package is `tasks`' business,
        and a hand-built stand-in would only agree with this suite's guess at it."""
        path = self.at(*parts)
        out = subprocess.run(["tasks", "pi-package", "--out", path],
                             text=True, capture_output=True, timeout=60)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        return path


class Upgrade(Recipe):

    def test_upgrading_a_home_that_was_never_created_is_refused(self):
        # `init` would happily build one, so a typo in SIANA_HOME would read as a
        # successful upgrade of a fleet that has nothing in it.
        missing = self.at("never-created")
        self.assertRefused(self.just("upgrade", home=missing),
                           "no SIANA home at", "just init")
        self.assertFalse(os.path.exists(missing))


class ContractDrift(Recipe):
    """A field the CLI writes and the home's contract lacks is refused by
    `extra: forbid` as a raw traceback, so it has to be caught before `add`."""

    def test_a_project_contract_missing_a_field_is_named_as_stale(self):
        self.contract("projects")
        with open(self.at("schema-projects.yaml")) as fh:
            text = fh.read()
        # Drop `qa`, the way a home written before that field looks.
        cut = text.split("  qa:")[0] + text.split("      behind every ship task in this project\n")[1]
        with open(self.at("schema-projects.yaml"), "w") as fh:
            fh.write(cut)
        out = self.just("doctor")
        self.assertIn("stale   schema-projects.yaml is missing: qa", out.stderr)
        self.assertIn("refuses to record them", out.stderr)

    def test_a_current_project_contract_is_not_called_stale(self):
        self.contract("projects")
        self.assertNotIn("schema-projects.yaml is missing", self.just("doctor").stderr)


class Doctor(Recipe):

    def watcher(self, **fields):
        """A watcher status record, written the way the watcher writes one."""
        with open(self.at(w.GRANT), "w") as fh:
            json.dump(fields, fh)
        return self.at(w.GRANT)

    def test_it_names_what_is_missing_from_an_empty_home(self):
        out = self.just("doctor")
        self.assertIn("missing AGENTS.md", out.stdout)
        self.assertIn("missing orders.md", out.stdout)

    def test_an_empty_store_is_a_zero_and_never_a_fault(self):
        # datafile writes the .jsonl on the first append, so absent-with-a-contract
        # is an empty store. Doctor must not cry wolf about it.
        self.contract("projects", "obligations")
        out = self.just("doctor").stdout
        self.assertIn("projects.jsonl (empty; written on the first project)", out)
        self.assertIn("obligations.jsonl (empty; written on the first promise)", out)

    def test_no_siana_running_is_the_ordinary_state(self):
        self.assertIn("no SIANA running", self.just("doctor").stdout)

    def test_a_session_whose_process_is_gone_is_called_stale(self):
        with open(self.at("session"), "w") as fh:
            fh.write(f"SIANA_PID={gone_pid()}\n")
        out = self.just("doctor")
        self.assertIn("stale   session claims pid", out.stderr)

    def test_no_watcher_is_said_out_loud_rather_than_left_to_be_assumed(self):
        # The state the whole record exists for. A quiet fleet and a stopped watcher
        # look identical, so silence here would be the captain assuming coverage.
        out = self.just("doctor")
        self.assertIn("no watcher (the fleet does not advance unattended)", out.stdout)

    def test_a_watcher_whose_process_is_running_is_reported_as_running(self):
        # This test's own process, because that is the only one here that is
        # certainly alive: the record is evidence about a process, and doctor asks
        # the operating system about it rather than believing the file.
        self.watcher(state="running", pid=os.getpid(),
                     command=w.process_command(os.getpid()), pane="w1:p1",
                     started="2026-08-28T08:00:00Z")
        out = self.just("doctor")
        self.assertIn(f"ok      watcher running (pid {os.getpid()}", out.stdout)
        self.assertNotIn("watcher", out.stderr)

    def test_a_watcher_that_stopped_is_named_with_its_reason_and_what_to_do(self):
        self.watcher(state="failed", pid=gone_pid(), command="/usr/bin/whatever",
                     pane="w1:p1", started="2026-08-28T08:00:00Z",
                     stopped="2026-08-28T09:00:00Z",
                     reason="pane w1:p1 is not running SIANA: herdr sees claude")
        out = self.just("doctor")
        self.assertIn("stale   watcher stopped at", out.stderr)
        self.assertIn("herdr sees claude", out.stderr)
        self.assertIn("start `siana-watch`", out.stderr)

    def test_a_watcher_that_died_without_saying_why_is_never_reported_healthy(self):
        self.watcher(state="running", pid=gone_pid(), command="/usr/bin/whatever",
                     pane="w1:p1", started="2026-08-28T08:00:00Z")
        out = self.just("doctor")
        self.assertIn("stale   watcher stopped without saying why", out.stderr)
        self.assertNotIn("watcher running", out.stdout)

    def test_a_stopped_watchers_record_is_reported_and_never_repaired(self):
        # Removing it is deciding the captain has read it, and doctor changes
        # nothing.
        path = self.watcher(state="failed", pid=gone_pid(), command="x",
                            reason="herdr went away")
        self.just("doctor")
        self.assertTrue(os.path.exists(path))


@unittest.skipUnless(has("pi") and has("tasks") and has("datafile"),
                     "init needs pi, tasks and datafile")
class Init(Recipe):
    """A real install into a throwaway home."""

    def test_a_fresh_home_is_one_the_rest_of_the_distro_can_read(self):
        out = self.just("init")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        for f in ("siana.env", "AGENTS.md", "orders.md", "brief-ship.md",
                  "brief-scout.md", "brief-qa.md", "schema-projects.yaml",
                  "schema-obligations.yaml", "schema-tasks.yaml"):
            self.assertTrue(os.path.exists(self.at(f)), f"init left out {f}")
        for c in ("siana", "siana-dispatch", "siana-brief", "siana-watch", "siana-owe",
                  "siana-publish", "siana-reap"):
            link = os.path.join(self.bindir, c)
            self.assertTrue(os.path.islink(link), f"{c} was not linked")
            # realpath both sides: what matters is that the link lands on this
            # distro's command, not how the path to it happens to be spelled. A
            # checkout under a symlinked prefix spells it two ways.
            self.assertEqual(os.path.realpath(link),
                             os.path.realpath(os.path.join(DISTRO, "bin", c)))
        doctor = self.just("doctor")
        self.assertNotIn("stale", doctor.stderr)
        # Nothing is tolerated here. The ambient queue used to depend on a tasks
        # checkout beside this one, so this had to excuse a missing
        # `.pi/settings.json` from a worktree - which meant the assertion was about
        # where the suite was checked out rather than about the install. `init`
        # generates the package from the installed `tasks` now, so a complete home
        # is complete everywhere.
        missing = [line.strip() for line in doctor.stdout.splitlines()
                   if "missing " in line]
        self.assertEqual(missing, [])

    def test_a_configured_pi_package_is_the_one_installed(self):
        # The captain who keeps their own package - a tasks checkout they are
        # editing - gets that one, not a generated copy that would shadow it.
        pkg = self.package("elsewhere", "pi-agent-tasks")
        out = self.just("init", pi_package=pkg)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertTrue(os.path.exists(self.at(".pi", "settings.json")))
        # And nothing was generated beside it, which is how a silent fallback to a
        # different package would show.
        self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_configured_pi_package_is_the_one_installed_through_the_environment(self):
        # The route the README documents, and the one the just variable shadows:
        # passing the variable at all would make this test the other one again.
        # Twice, because an install the captain repeats has to stay the one they
        # asked for rather than drift to a generated package on the second run.
        pkg = self.package("own-package")
        for _ in range(2):
            out = self.just("init", pi_package=None,
                            env={"SIANA_PI_PACKAGE": pkg})
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            with open(self.at(".pi", "settings.json")) as fh:
                self.assertIn("own-package", fh.read())
            self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_configured_pi_package_that_is_absent_is_refused(self):
        # Never a fallback: generating a different package behind the captain's
        # back gives SIANA a queue skill that is not the one they pointed at. And
        # the refusal comes before anything is written, so a typo costs a retype.
        gone = os.path.join(self.home, "not-a-package")
        self.assertRefused(self.just("init", pi_package=gone),
                           "no pi package directory at", "SIANA_PI_PACKAGE")
        self.assertFalse(os.path.exists(self.at("siana.env")))

    def test_a_configured_directory_that_is_no_package_is_refused(self):
        # The near miss, and the one that used to get through: a tasks checkout
        # root rather than the `pi-agent-tasks` package inside it. `pi install`
        # accepts any directory, so init exited 0 with a settings.json naming a
        # directory holding no package - a home `doctor` called complete with no
        # queue in front of SIANA. Existing and a directory is not enough.
        checkout = os.path.join(self.home, "checkout")
        self.package(os.path.join("checkout", "pi-agent-tasks"))
        self.assertRefused(self.just("init", pi_package=checkout),
                           "not a pi package", "no package.json in", "SIANA_PI_PACKAGE")
        # Nothing was written, and above all no settings.json naming it: a home
        # that half exists is recoverable, one that looks installed is not.
        self.assertFalse(os.path.exists(self.at("siana.env")))
        self.assertFalse(os.path.exists(self.at(".pi", "settings.json")))
        self.assertFalse(os.path.exists(self.at("pi-agent-tasks")))

    def test_a_directory_that_is_no_package_is_refused_through_the_environment(self):
        checkout = os.path.join(self.home, "checkout")
        self.package(os.path.join("checkout", "pi-agent-tasks"))
        self.assertRefused(
            self.just("init", pi_package=None, env={"SIANA_PI_PACKAGE": checkout}),
            "not a pi package", "no package.json in")
        self.assertFalse(os.path.exists(self.at(".pi", "settings.json")))

    def test_it_is_idempotent_and_never_clobbers_an_evolved_file(self):
        # SIANA can evolve its own instructions, so a diverged home copy is the
        # captain's work and not drift to be cleaned up.
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("AGENTS.md"), "a") as fh:
            fh.write("\nThe captain prefers reports at noon.\n")
        again = self.just("init")
        self.assertEqual(again.returncode, 0, again.stdout + again.stderr)
        self.assertIn("kept     ", again.stdout)
        with open(self.at("AGENTS.md")) as fh:
            self.assertIn("reports at noon", fh.read())

    def test_uninstall_removes_the_links_and_leaves_the_home_alone(self):
        self.assertEqual(self.just("init").returncode, 0)
        out = self.just("uninstall")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.bindir, "siana")))
        self.assertTrue(os.path.exists(self.at("tasks.jsonl")) or
                        os.path.exists(self.at("schema-tasks.yaml")))
        self.assertIn("kept    ", out.stdout)

    def test_uninstall_refuses_to_remove_something_it_did_not_install(self):
        os.makedirs(self.bindir, exist_ok=True)
        with open(os.path.join(self.bindir, "siana"), "w") as fh:
            fh.write("#!/bin/sh\n")
        self.assertRefused(self.just("uninstall"), "refusing to remove")
        self.assertTrue(os.path.exists(os.path.join(self.bindir, "siana")))

    def test_upgrade_preserves_an_evolved_file_with_the_diff_beside_it(self):
        self.assertEqual(self.just("init").returncode, 0)
        with open(self.at("orders.md"), "w") as fh:
            fh.write("# My own orders\n")
        out = self.just("upgrade")
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        self.assertIn("upgraded ", out.stdout)
        backups = []
        for root, _, files in os.walk(self.at("upgrade")):
            backups += [os.path.join(root, f) for f in files]
        kept = [b for b in backups if b.endswith("orders.md")]
        diffs = [b for b in backups if b.endswith("orders.md.diff")]
        self.assertTrue(kept, f"the captain's copy was not preserved: {backups}")
        self.assertTrue(diffs, f"no diff was left beside it: {backups}")
        with open(kept[0]) as fh:
            self.assertIn("My own orders", fh.read())
        with open(self.at("orders.md")) as fh:
            self.assertIn("Standing orders", fh.read())


if __name__ == "__main__":
    unittest.main()
